export interface HotelMetrics {
  name: string;
  ebitPct: number;
  netIncome: number;
  goppar: number;
  cumulativeEarnings: number;
  adr: number;
  revpar: number;
  revpor: number;
  restaurantRevPerCustomer: number;
  hotelCostPerAvailableRoom: number;
  hotelCostPerOccupiedRoom: number;
  restaurantCostPerCustomer: number;
  occupancyPct: number;
  restaurantCustomersPerSeat: number;
  hotelSatisfaction: number;
  restaurantSatisfaction: number;
  staffSatisfaction: number;
  personnelCostPct: number;
  mpi: number;
  ari: number;
  rgi: number;
  cmpi: number;
  cari: number;
  crgi: number;
}

export interface UniverseData {
  id: string;
  number: number;
  title: string;
  subtitle: string;
  simulationName: string;
  round: string;
  totalHotels: number;
  description: string;
  topPerformer: string;
  topPerformerReason: string;
  bottomPerformer: string;
  bottomPerformerReason: string;
  keyInsights: string[];
  hotels: HotelMetrics[];
}

export const UNIVERSES_DATA: UniverseData[] = [
  {
    id: "universe-1",
    number: 1,
    title: "Universe 1 - Market Benchmark",
    subtitle: "IHM Hyderabad Hospitality Management - Round 9 Simulation Report",
    simulationName: "IHM Hyderabad Hospitality Management Feb 2026 - Universe 1",
    round: "Round 9",
    totalHotels: 11,
    description:
      "Celestia and Victory Hotels lead 11 competing hotels with top margins and operational efficiency.",
    topPerformer: "Celestia",
    topPerformerReason:
      "Achieved highest operating profit (31% EBIT), strongest RevPAR (€85), highest occupancy (81%), and top Revenue Generation Index (138.34 RGI).",
    bottomPerformer: "Navy",
    bottomPerformerReason:
      "High room prices (€124 ADR) could not compensate for extreme personnel cost ratio (86.6% of revenue), low occupancy (39%), and massive net losses (-€63,797).",
    keyInsights: [
      "Celestia is the overall market champion with 30% EBIT %, €67,243 net income, and 81% occupancy.",
      "Victory Hotels leads in long-term cumulative earnings (€497,486) by maintaining steady 19% operating margins.",
      "Brown shows strong operational balance with 24% EBIT %, €34,057 net income, and top staff satisfaction (3.76/5).",
      "Marriott has accumulated heavy historical losses (-€513,270 cumulative) despite a modest RevPAR of €76.",
      "Navy suffers from excessive restaurant cost per customer (€2,479) and an unused dining room (0.0 customers/seat).",
    ],
    hotels: [
      {
        name: "Celestia",
        ebitPct: 30,
        netIncome: 67243,
        goppar: 53,
        cumulativeEarnings: 473407,
        adr: 105,
        revpar: 85,
        revpor: 143,
        restaurantRevPerCustomer: 23,
        hotelCostPerAvailableRoom: 63,
        hotelCostPerOccupiedRoom: 78,
        restaurantCostPerCustomer: 21,
        occupancyPct: 81,
        restaurantCustomersPerSeat: 4.1,
        hotelSatisfaction: 3.65,
        restaurantSatisfaction: 4.02,
        staffSatisfaction: 3.69,
        personnelCostPct: 28.8,
        mpi: 149.16,
        ari: 91.89,
        rgi: 138.34,
        cmpi: 127.06,
        cari: 97.17,
        crgi: 121.99,
      },
      {
        name: "Victory Hotels",
        ebitPct: 19,
        netIncome: 26604,
        goppar: 36,
        cumulativeEarnings: 497486,
        adr: 109,
        revpar: 71,
        revpor: 141,
        restaurantRevPerCustomer: 24,
        hotelCostPerAvailableRoom: 56,
        hotelCostPerOccupiedRoom: 86,
        restaurantCostPerCustomer: 32,
        occupancyPct: 65,
        restaurantCustomersPerSeat: 1.9,
        hotelSatisfaction: 2.89,
        restaurantSatisfaction: 3.05,
        staffSatisfaction: 2.42,
        personnelCostPct: 44.4,
        mpi: 115.83,
        ari: 95.74,
        rgi: 112.23,
        cmpi: 112.81,
        cari: 100.74,
        crgi: 114.22,
      },
      {
        name: "Hyatt Hotels",
        ebitPct: 4,
        netIncome: 2408,
        goppar: 21,
        cumulativeEarnings: 121218,
        adr: 124,
        revpar: 62,
        revpor: 151,
        restaurantRevPerCustomer: 20,
        hotelCostPerAvailableRoom: 54,
        hotelCostPerOccupiedRoom: 109,
        restaurantCostPerCustomer: 35,
        occupancyPct: 50,
        restaurantCustomersPerSeat: 1.5,
        hotelSatisfaction: 2.63,
        restaurantSatisfaction: 2.44,
        staffSatisfaction: 2.24,
        personnelCostPct: 60.7,
        mpi: 86.49,
        ari: 109.99,
        rgi: 96.2,
        cmpi: 80.81,
        cari: 105.31,
        crgi: 84.86,
      },
      {
        name: "Hilton Hotels",
        ebitPct: 18,
        netIncome: 22452,
        goppar: 26,
        cumulativeEarnings: 401476,
        adr: 105,
        revpar: 59,
        revpor: 140,
        restaurantRevPerCustomer: 13,
        hotelCostPerAvailableRoom: 53,
        hotelCostPerOccupiedRoom: 94,
        restaurantCostPerCustomer: 14,
        occupancyPct: 56,
        restaurantCustomersPerSeat: 1.9,
        hotelSatisfaction: 3.46,
        restaurantSatisfaction: 3.43,
        staffSatisfaction: 3.73,
        personnelCostPct: 42.8,
        mpi: 98.06,
        ari: 91.99,
        rgi: 91.33,
        cmpi: 109.41,
        cari: 93.68,
        crgi: 103.37,
      },
      {
        name: "Legends",
        ebitPct: 5,
        netIncome: 4105,
        goppar: 26,
        cumulativeEarnings: 196252,
        adr: 107,
        revpar: 61,
        revpor: 141,
        restaurantRevPerCustomer: 22,
        hotelCostPerAvailableRoom: 54,
        hotelCostPerOccupiedRoom: 96,
        restaurantCostPerCustomer: 40,
        occupancyPct: 57,
        restaurantCustomersPerSeat: 1.3,
        hotelSatisfaction: 3.01,
        restaurantSatisfaction: 2.93,
        staffSatisfaction: 3.16,
        personnelCostPct: 52.8,
        mpi: 99.73,
        ari: 94.27,
        rgi: 95.19,
        cmpi: 100.33,
        cari: 99.0,
        crgi: 99.77,
      },
      {
        name: "Ochre",
        ebitPct: -24,
        netIncome: -27133,
        goppar: 6,
        cumulativeEarnings: 76092,
        adr: 119,
        revpar: 39,
        revpor: 146,
        restaurantRevPerCustomer: 28,
        hotelCostPerAvailableRoom: 43,
        hotelCostPerOccupiedRoom: 129,
        restaurantCostPerCustomer: 145,
        occupancyPct: 33,
        restaurantCustomersPerSeat: 0.1,
        hotelSatisfaction: 2.7,
        restaurantSatisfaction: 2.18,
        staffSatisfaction: 1.99,
        personnelCostPct: 74.4,
        mpi: 55.56,
        ari: 105.16,
        rgi: 59.01,
        cmpi: 75.65,
        cari: 103.5,
        crgi: 78.28,
      },
      {
        name: "Taj Hotels",
        ebitPct: 5,
        netIncome: 2690,
        goppar: 19,
        cumulativeEarnings: 251696,
        adr: 121,
        revpar: 55,
        revpor: 146,
        restaurantRevPerCustomer: 21,
        hotelCostPerAvailableRoom: 48,
        hotelCostPerOccupiedRoom: 104,
        restaurantCostPerCustomer: 34,
        occupancyPct: 46,
        restaurantCustomersPerSeat: 1.4,
        hotelSatisfaction: 2.9,
        restaurantSatisfaction: 2.81,
        staffSatisfaction: 2.42,
        personnelCostPct: 57.1,
        mpi: 79.23,
        ari: 106.95,
        rgi: 85.67,
        cmpi: 98.69,
        cari: 102.11,
        crgi: 101.08,
      },
      {
        name: "Navy",
        ebitPct: -52,
        netIncome: -63797,
        goppar: -3,
        cumulativeEarnings: 247101,
        adr: 124,
        revpar: 48,
        revpor: 153,
        restaurantRevPerCustomer: 34,
        hotelCostPerAvailableRoom: 63,
        hotelCostPerOccupiedRoom: 161,
        restaurantCostPerCustomer: 2479,
        occupancyPct: 39,
        restaurantCustomersPerSeat: 0.0,
        hotelSatisfaction: 3.59,
        restaurantSatisfaction: 3.3,
        staffSatisfaction: 3.75,
        personnelCostPct: 86.6,
        mpi: 66.29,
        ari: 110.33,
        rgi: 73.79,
        cmpi: 109.04,
        cari: 100.84,
        crgi: 109.93,
      },
      {
        name: "Marriott",
        ebitPct: -4,
        netIncome: -14958,
        goppar: 40,
        cumulativeEarnings: -513270,
        adr: 107,
        revpar: 76,
        revpor: 143,
        restaurantRevPerCustomer: 21,
        hotelCostPerAvailableRoom: 62,
        hotelCostPerOccupiedRoom: 87,
        restaurantCostPerCustomer: 47,
        occupancyPct: 71,
        restaurantCustomersPerSeat: 2.5,
        hotelSatisfaction: 3.29,
        restaurantSatisfaction: 3.46,
        staffSatisfaction: 3.44,
        personnelCostPct: 36.6,
        mpi: 127.93,
        ari: 93.69,
        rgi: 121.19,
        cmpi: 111.43,
        cari: 95.38,
        crgi: 106.68,
      },
      {
        name: "ITC Hotels",
        ebitPct: 5,
        netIncome: 5639,
        goppar: 17,
        cumulativeEarnings: 62368,
        adr: 115,
        revpar: 69,
        revpor: 154,
        restaurantRevPerCustomer: 20,
        hotelCostPerAvailableRoom: 74,
        hotelCostPerOccupiedRoom: 125,
        restaurantCostPerCustomer: 26,
        occupancyPct: 60,
        restaurantCustomersPerSeat: 1.1,
        hotelSatisfaction: 4.19,
        restaurantSatisfaction: 3.31,
        staffSatisfaction: 3.79,
        personnelCostPct: 54.8,
        mpi: 105.58,
        ari: 101.23,
        rgi: 108.22,
        cmpi: 88.2,
        cari: 99.09,
        crgi: 88.06,
      },
      {
        name: "Brown",
        ebitPct: 24,
        netIncome: 34057,
        goppar: 36,
        cumulativeEarnings: 199330,
        adr: 113,
        revpar: 77,
        revpor: 141,
        restaurantRevPerCustomer: 17,
        hotelCostPerAvailableRoom: 60,
        hotelCostPerOccupiedRoom: 88,
        restaurantCostPerCustomer: 20,
        occupancyPct: 69,
        restaurantCustomersPerSeat: 1.4,
        hotelSatisfaction: 3.51,
        restaurantSatisfaction: 3.45,
        staffSatisfaction: 3.76,
        personnelCostPct: 42.4,
        mpi: 123.18,
        ari: 99.21,
        rgi: 123.74,
        cmpi: 93.16,
        cari: 103.48,
        crgi: 96.76,
      },
    ],
  },
  {
    id: "universe-2",
    number: 2,
    title: "Universe 2 - Volume vs Margin Strategy",
    subtitle: "IHM Hyderabad Hospitality Management - Round 9 Simulation Report",
    simulationName: "IHM Hyderabad Hospitality Management Feb 2026 - Universe 2",
    round: "Round 9",
    totalHotels: 11,
    description:
      "Green Park drives 97% occupancy while ITC Hotels achieves top cumulative earnings.",
    topPerformer: "Green Park Hotel & ITC Hotels",
    topPerformerReason:
      "Green Park Hotel delivered the highest EBIT % (29%), Net Income (€48,827), and 97% occupancy. ITC Hotels built the highest cumulative earnings (€405,128).",
    bottomPerformer: "Marriott",
    bottomPerformerReason:
      "Recorded severe operating loss (-39% EBIT, -€39,941 net income), lowest occupancy (33%), and excessive employee cost ratio (84.3%).",
    keyInsights: [
      "Green Park Hotel achieved a phenomenal 97% occupancy by keeping ADR competitive (€82), resulting in €48,827 net income.",
      "ITC Hotels generated €405,128 in cumulative earnings with a solid 24% EBIT margin and 71% occupancy.",
      "Taj earned the highest customer satisfaction (4.51/5) and staff satisfaction (4.93/5) along with top RevPAR (€89), but carries historical losses from earlier rounds.",
      "Blue and Navy remain strong cumulative profit generators (€380,192 and €317,418 respectively).",
      "Marriott's restaurant suffered 0.0 customers/seat alongside €319 cost per restaurant customer.",
    ],
    hotels: [
      {
        name: "Accor Hotels",
        ebitPct: 7,
        netIncome: 7501,
        goppar: 28,
        cumulativeEarnings: 264535,
        adr: 103,
        revpar: 70,
        revpor: 136,
        restaurantRevPerCustomer: 27,
        hotelCostPerAvailableRoom: 65,
        hotelCostPerOccupiedRoom: 95,
        restaurantCostPerCustomer: 63,
        occupancyPct: 68,
        restaurantCustomersPerSeat: 0.9,
        hotelSatisfaction: 3.75,
        restaurantSatisfaction: 3.49,
        staffSatisfaction: 3.74,
        personnelCostPct: 56.8,
        mpi: 114.62,
        ari: 94.6,
        rgi: 110.79,
        cmpi: 94.2,
        cari: 104.52,
        crgi: 98.2,
      },
      {
        name: "Marriott",
        ebitPct: -39,
        netIncome: -39941,
        goppar: -3,
        cumulativeEarnings: -74677,
        adr: 111,
        revpar: 37,
        revpor: 141,
        restaurantRevPerCustomer: 36,
        hotelCostPerAvailableRoom: 49,
        hotelCostPerOccupiedRoom: 150,
        restaurantCostPerCustomer: 319,
        occupancyPct: 33,
        restaurantCustomersPerSeat: 0.0,
        hotelSatisfaction: 4.04,
        restaurantSatisfaction: 3.09,
        staffSatisfaction: 3.28,
        personnelCostPct: 84.3,
        mpi: 52.24,
        ari: 102.56,
        rgi: 54.67,
        cmpi: 73.63,
        cari: 97.49,
        crgi: 72.23,
      },
      {
        name: "Blue",
        ebitPct: 11,
        netIncome: 12580,
        goppar: 20,
        cumulativeEarnings: 380192,
        adr: 108,
        revpar: 55,
        revpor: 145,
        restaurantRevPerCustomer: 14,
        hotelCostPerAvailableRoom: 53,
        hotelCostPerOccupiedRoom: 105,
        restaurantCostPerCustomer: 15,
        occupancyPct: 50,
        restaurantCustomersPerSeat: 2.8,
        hotelSatisfaction: 3.37,
        restaurantSatisfaction: 3.41,
        staffSatisfaction: 3.57,
        personnelCostPct: 46.2,
        mpi: 81.95,
        ari: 99.99,
        rgi: 83.74,
        cmpi: 110.89,
        cari: 95.64,
        crgi: 106.05,
      },
      {
        name: "ITC Hotels",
        ebitPct: 24,
        netIncome: 41160,
        goppar: 43,
        cumulativeEarnings: 405128,
        adr: 111,
        revpar: 79,
        revpor: 146,
        restaurantRevPerCustomer: 19,
        hotelCostPerAvailableRoom: 61,
        hotelCostPerOccupiedRoom: 86,
        restaurantCostPerCustomer: 22,
        occupancyPct: 71,
        restaurantCustomersPerSeat: 2.4,
        hotelSatisfaction: 3.29,
        restaurantSatisfaction: 3.2,
        staffSatisfaction: 2.81,
        personnelCostPct: 41.6,
        mpi: 120.37,
        ari: 102.31,
        rgi: 126.02,
        cmpi: 148.9,
        cari: 97.8,
        crgi: 145.98,
      },
      {
        name: "Taj",
        ebitPct: 19,
        netIncome: 32356,
        goppar: 36,
        cumulativeEarnings: -264701,
        adr: 109,
        revpar: 89,
        revpor: 157,
        restaurantRevPerCustomer: 20,
        hotelCostPerAvailableRoom: 92,
        hotelCostPerOccupiedRoom: 113,
        restaurantCostPerCustomer: 21,
        occupancyPct: 82,
        restaurantCustomersPerSeat: 1.6,
        hotelSatisfaction: 4.51,
        restaurantSatisfaction: 3.76,
        staffSatisfaction: 4.93,
        personnelCostPct: 45.5,
        mpi: 139.77,
        ari: 100.84,
        rgi: 144.26,
        cmpi: 98.69,
        cari: 99.96,
        crgi: 98.54,
      },
      {
        name: "Leela",
        ebitPct: -4,
        netIncome: -11869,
        goppar: 23,
        cumulativeEarnings: -55903,
        adr: 114,
        revpar: 54,
        revpor: 159,
        restaurantRevPerCustomer: 11,
        hotelCostPerAvailableRoom: 52,
        hotelCostPerOccupiedRoom: 111,
        restaurantCostPerCustomer: 17,
        occupancyPct: 47,
        restaurantCustomersPerSeat: 5.8,
        hotelSatisfaction: 3.65,
        restaurantSatisfaction: 3.99,
        staffSatisfaction: 3.77,
        personnelCostPct: 47.9,
        mpi: 76.14,
        ari: 105.9,
        rgi: 82.3,
        cmpi: 87.6,
        cari: 101.01,
        crgi: 88.91,
      },
      {
        name: "HYATT",
        ebitPct: 19,
        netIncome: 28321,
        goppar: 24,
        cumulativeEarnings: 206161,
        adr: 112,
        revpar: 62,
        revpor: 152,
        restaurantRevPerCustomer: 22,
        hotelCostPerAvailableRoom: 60,
        hotelCostPerOccupiedRoom: 108,
        restaurantCostPerCustomer: 18,
        occupancyPct: 55,
        restaurantCustomersPerSeat: 3.5,
        hotelSatisfaction: 4.02,
        restaurantSatisfaction: 3.97,
        staffSatisfaction: 4.53,
        personnelCostPct: 44.6,
        mpi: 90.28,
        ari: 104.03,
        rgi: 95.97,
        cmpi: 92.42,
        cari: 102.85,
        crgi: 95.56,
      },
      {
        name: "NAVY",
        ebitPct: 6,
        netIncome: 4216,
        goppar: 19,
        cumulativeEarnings: 317418,
        adr: 117,
        revpar: 50,
        revpor: 144,
        restaurantRevPerCustomer: 19,
        hotelCostPerAvailableRoom: 43,
        hotelCostPerOccupiedRoom: 99,
        restaurantCostPerCustomer: 28,
        occupancyPct: 43,
        restaurantCustomersPerSeat: 1.3,
        hotelSatisfaction: 2.41,
        restaurantSatisfaction: 2.13,
        staffSatisfaction: 1.62,
        personnelCostPct: 47.8,
        mpi: 69.08,
        ari: 108.31,
        rgi: 76.27,
        cmpi: 95.87,
        cari: 104.11,
        crgi: 99.9,
      },
      {
        name: "Green Park Hotel",
        ebitPct: 29,
        netIncome: 48827,
        goppar: 45,
        cumulativeEarnings: 164732,
        adr: 82,
        revpar: 79,
        revpor: 110,
        restaurantRevPerCustomer: 12,
        hotelCostPerAvailableRoom: 62,
        hotelCostPerOccupiedRoom: 64,
        restaurantCostPerCustomer: 13,
        occupancyPct: 97,
        restaurantCustomersPerSeat: 1.7,
        hotelSatisfaction: 2.82,
        restaurantSatisfaction: 2.51,
        staffSatisfaction: 1.69,
        personnelCostPct: 28.3,
        mpi: 170.59,
        ari: 73.38,
        rgi: 125.89,
        cmpi: 110.43,
        cari: 94.09,
        crgi: 101.02,
      },
      {
        name: "IHG Hotels",
        ebitPct: 1,
        netIncome: -1814,
        goppar: 19,
        cumulativeEarnings: 212402,
        adr: 123,
        revpar: 64,
        revpor: 157,
        restaurantRevPerCustomer: 20,
        hotelCostPerAvailableRoom: 63,
        hotelCostPerOccupiedRoom: 120,
        restaurantCostPerCustomer: 53,
        occupancyPct: 52,
        restaurantCustomersPerSeat: 0.5,
        hotelSatisfaction: 3.65,
        restaurantSatisfaction: 3.28,
        staffSatisfaction: 3.83,
        personnelCostPct: 60.9,
        mpi: 85.65,
        ari: 114.63,
        rgi: 100.18,
        cmpi: 104.84,
        cari: 105.86,
        crgi: 111.5,
      },
      {
        name: "The Park Hotels",
        ebitPct: 1,
        netIncome: -5620,
        goppar: 31,
        cumulativeEarnings: -97340,
        adr: 103,
        revpar: 68,
        revpor: 143,
        restaurantRevPerCustomer: 25,
        hotelCostPerAvailableRoom: 63,
        hotelCostPerOccupiedRoom: 96,
        restaurantCostPerCustomer: 101,
        occupancyPct: 66,
        restaurantCustomersPerSeat: 0.7,
        hotelSatisfaction: 3.65,
        restaurantSatisfaction: 3.74,
        staffSatisfaction: 4.02,
        personnelCostPct: 49.9,
        mpi: 109.78,
        ari: 94.48,
        rgi: 105.99,
        cmpi: 90.05,
        cari: 97.14,
        crgi: 88.4,
      },
    ],
  },
  {
    id: "universe-3",
    number: 3,
    title: "Universe 3 - Efficiency & Premium Dynamics",
    subtitle: "IHM Hyderabad Hospitality Management - Round 9 Simulation Report",
    simulationName: "IHM Hyderabad Hospitality Management Feb 2026 - Universe 3",
    round: "Round 9",
    totalHotels: 10,
    description:
      "Hotel Krat and Lemon Tree lead 10 hotels with top profits and market penetration.",
    topPerformer: "Hotel Krat & Lemon Tree",
    topPerformerReason:
      "Hotel Krat earned €61,219 net income with €490,990 cumulative earnings. Lemon Tree generated top market penetration (154.82 MPI) and 81% occupancy.",
    bottomPerformer: "Radisson",
    bottomPerformerReason:
      "Operated at a -28% EBIT loss, -€56,659 net income, -12 GOPPAR, and accumulated €203,945 in total losses due to 89% personnel cost ratios.",
    keyInsights: [
      "Hotel Krat is the star performer with €61,219 Round 9 profit, €490,990 cumulative earnings, and 4.96/5 staff satisfaction.",
      "Lemon Tree dominated overall revenue generation (147.73 RGI) with €88 RevPAR and 81% hotel occupancy.",
      "ITC HOTELS delivered the highest EBIT margin (31%) and lowest occupied room cost (€55), but recorded lowest staff satisfaction (1.46/5).",
      "Hyatt delivered excellent hotel customer satisfaction (4.36/5) and healthy 17% operating margins.",
      "Radisson and ACCOR struggled under heavy personnel costs (89.0% and 87.1% of revenue respectively).",
    ],
    hotels: [
      {
        name: "Lemon tree",
        ebitPct: 20,
        netIncome: 33716,
        goppar: 44,
        cumulativeEarnings: 473731,
        adr: 108,
        revpar: 88,
        revpor: 141,
        restaurantRevPerCustomer: 18,
        hotelCostPerAvailableRoom: 71,
        hotelCostPerOccupiedRoom: 87,
        restaurantCostPerCustomer: 29,
        occupancyPct: 81,
        restaurantCustomersPerSeat: 1.6,
        hotelSatisfaction: 3.73,
        restaurantSatisfaction: 3.63,
        staffSatisfaction: 3.19,
        personnelCostPct: 41.1,
        mpi: 154.82,
        ari: 95.47,
        rgi: 147.73,
        cmpi: 126.76,
        cari: 94.43,
        crgi: 119.64,
      },
      {
        name: "Hyatt",
        ebitPct: 17,
        netIncome: 25689,
        goppar: 26,
        cumulativeEarnings: 338320,
        adr: 119,
        revpar: 67,
        revpor: 166,
        restaurantRevPerCustomer: 22,
        hotelCostPerAvailableRoom: 67,
        hotelCostPerOccupiedRoom: 119,
        restaurantCostPerCustomer: 21,
        occupancyPct: 56,
        restaurantCustomersPerSeat: 2.0,
        hotelSatisfaction: 4.36,
        restaurantSatisfaction: 3.71,
        staffSatisfaction: 3.95,
        personnelCostPct: 47.6,
        mpi: 100.95,
        ari: 105.89,
        rgi: 107.11,
        cmpi: 97.34,
        cari: 105.23,
        crgi: 102.89,
      },
      {
        name: "Hotel Krat",
        ebitPct: 29,
        netIncome: 61219,
        goppar: 45,
        cumulativeEarnings: 490990,
        adr: 123,
        revpar: 82,
        revpor: 173,
        restaurantRevPerCustomer: 22,
        hotelCostPerAvailableRoom: 69,
        hotelCostPerOccupiedRoom: 105,
        restaurantCostPerCustomer: 17,
        occupancyPct: 66,
        restaurantCustomersPerSeat: 3.4,
        hotelSatisfaction: 4.19,
        restaurantSatisfaction: 4.25,
        staffSatisfaction: 4.96,
        personnelCostPct: 37.3,
        mpi: 122.08,
        ari: 110.3,
        rgi: 135.23,
        cmpi: 106.49,
        cari: 106.95,
        crgi: 114.89,
      },
      {
        name: "ACCOR",
        ebitPct: -25,
        netIncome: -49118,
        goppar: -8,
        cumulativeEarnings: -32485,
        adr: 118,
        revpar: 62,
        revpor: 155,
        restaurantRevPerCustomer: 15,
        hotelCostPerAvailableRoom: 90,
        hotelCostPerOccupiedRoom: 171,
        restaurantCostPerCustomer: 27,
        occupancyPct: 52,
        restaurantCustomersPerSeat: 0.9,
        hotelSatisfaction: 3.32,
        restaurantSatisfaction: 3.2,
        staffSatisfaction: 3.37,
        personnelCostPct: 87.1,
        mpi: 94.03,
        ari: 104.63,
        rgi: 98.55,
        cmpi: 82.73,
        cari: 107.07,
        crgi: 88.82,
      },
      {
        name: "Taj Hotels",
        ebitPct: -24,
        netIncome: -39478,
        goppar: 4,
        cumulativeEarnings: 239704,
        adr: 114,
        revpar: 50,
        revpor: 135,
        restaurantRevPerCustomer: 19,
        hotelCostPerAvailableRoom: 56,
        hotelCostPerOccupiedRoom: 127,
        restaurantCostPerCustomer: 36,
        occupancyPct: 44,
        restaurantCustomersPerSeat: 2.0,
        hotelSatisfaction: 2.99,
        restaurantSatisfaction: 2.8,
        staffSatisfaction: 1.97,
        personnelCostPct: 84.0,
        mpi: 77.44,
        ari: 101.21,
        rgi: 78.51,
        cmpi: 100.56,
        cari: 100.75,
        crgi: 101.84,
      },
      {
        name: "ITC HOTELS",
        ebitPct: 31,
        netIncome: 32109,
        goppar: 40,
        cumulativeEarnings: 290984,
        adr: 104,
        revpar: 58,
        revpor: 127,
        restaurantRevPerCustomer: 17,
        hotelCostPerAvailableRoom: 31,
        hotelCostPerOccupiedRoom: 55,
        restaurantCostPerCustomer: 28,
        occupancyPct: 55,
        restaurantCustomersPerSeat: 1.2,
        hotelSatisfaction: 2.34,
        restaurantSatisfaction: 2.3,
        staffSatisfaction: 1.46,
        personnelCostPct: 32.3,
        mpi: 100.03,
        ari: 91.08,
        rgi: 91.28,
        cmpi: 107.92,
        cari: 93.96,
        crgi: 99.84,
      },
      {
        name: "The leela",
        ebitPct: 12,
        netIncome: 19605,
        goppar: 24,
        cumulativeEarnings: -8657,
        adr: 104,
        revpar: 61,
        revpor: 144,
        restaurantRevPerCustomer: 21,
        hotelCostPerAvailableRoom: 60,
        hotelCostPerOccupiedRoom: 102,
        restaurantCostPerCustomer: 27,
        occupancyPct: 59,
        restaurantCustomersPerSeat: 1.4,
        hotelSatisfaction: 3.57,
        restaurantSatisfaction: 3.39,
        staffSatisfaction: 4.28,
        personnelCostPct: 50.8,
        mpi: 107.14,
        ari: 90.93,
        rgi: 97.54,
        cmpi: 99.64,
        cari: 96.79,
        crgi: 96.46,
      },
      {
        name: "Radisson",
        ebitPct: -28,
        netIncome: -56659,
        goppar: -12,
        cumulativeEarnings: -203945,
        adr: 110,
        revpar: 60,
        revpor: 146,
        restaurantRevPerCustomer: 16,
        hotelCostPerAvailableRoom: 92,
        hotelCostPerOccupiedRoom: 170,
        restaurantCostPerCustomer: 22,
        occupancyPct: 54,
        restaurantCustomersPerSeat: 2.4,
        hotelSatisfaction: 3.12,
        restaurantSatisfaction: 3.04,
        staffSatisfaction: 3.47,
        personnelCostPct: 89.0,
        mpi: 97.18,
        ari: 97.35,
        rgi: 94.79,
        cmpi: 95.5,
        cari: 97.47,
        crgi: 93.28,
      },
      {
        name: "Green park hotel",
        ebitPct: -12,
        netIncome: -25177,
        goppar: 5,
        cumulativeEarnings: 156485,
        adr: 115,
        revpar: 46,
        revpor: 148,
        restaurantRevPerCustomer: 14,
        hotelCostPerAvailableRoom: 54,
        hotelCostPerOccupiedRoom: 135,
        restaurantCostPerCustomer: 18,
        occupancyPct: 40,
        restaurantCustomersPerSeat: 3.2,
        hotelSatisfaction: 3.75,
        restaurantSatisfaction: 3.84,
        staffSatisfaction: 4.45,
        personnelCostPct: 59.8,
        mpi: 69.21,
        ari: 101.91,
        rgi: 70.62,
        cmpi: 87.91,
        cari: 98.14,
        crgi: 86.22,
      },
      {
        name: "Trident",
        ebitPct: -7,
        netIncome: -15328,
        goppar: 5,
        cumulativeEarnings: 214648,
        adr: 115,
        revpar: 53,
        revpor: 150,
        restaurantRevPerCustomer: 14,
        hotelCostPerAvailableRoom: 64,
        hotelCostPerOccupiedRoom: 138,
        restaurantCostPerCustomer: 16,
        occupancyPct: 46,
        restaurantCustomersPerSeat: 2.8,
        hotelSatisfaction: 3.33,
        restaurantSatisfaction: 3.34,
        staffSatisfaction: 3.36,
        personnelCostPct: 61.4,
        mpi: 82.35,
        ari: 101.6,
        rgi: 83.8,
        cmpi: 98.59,
        cari: 99.58,
        crgi: 98.62,
      },
    ],
  },
  {
    id: "universe-4",
    number: 4,
    title: "Universe 4 - High Competition & Cost Crisis",
    subtitle: "IHM Hyderabad Hospitality Management - Round 9 Simulation Report",
    simulationName: "IHM Hyderabad Hospitality Management Feb 2026 - Universe 4",
    round: "Round 9",
    totalHotels: 12,
    description:
      "Lemontree and ITC Hotel lead 12 hotels while Marriott faces high structural costs.",
    topPerformer: "Lemontree & ITC Hotel",
    topPerformerReason:
      "Lemontree earned €67,404 Net Income, €478,266 cumulative earnings, and 31% EBIT margin. ITC Hotel posted 90% occupancy and 4.42/5 customer satisfaction.",
    bottomPerformer: "Marriott Hotel",
    bottomPerformerReason:
      "Collapsed with -293% EBIT %, -€428,390 Net Income in Round 9 alone, €460 occupied room costs, 340.3% personnel cost ratio, and -€1,197,288 total cumulative losses.",
    keyInsights: [
      "Lemontree achieved top operational performance: 31% EBIT %, €67,404 net income, €57 GOPPAR, and 83% occupancy.",
      "ITC Hotel achieved 90% occupancy, €99 RevPAR, 4.42/5 customer satisfaction, and 4.72/5 staff satisfaction.",
      "Hilton Hotels and Radisson Hotels posted strong cumulative profits (€452,358 and €418,581 respectively).",
      "Marriott Hotel experienced a historic collapse due to cost per occupied room (€460) and employee expense ratio (340.3% of revenue).",
      "Hyatt Hotels incurred €279 in restaurant cost per customer alongside 0.1 restaurant customers per seat.",
    ],
    hotels: [
      {
        name: "Marriott Hotel",
        ebitPct: -293,
        netIncome: -428390,
        goppar: -118,
        cumulativeEarnings: -1197288,
        adr: 128,
        revpar: 51,
        revpor: 161,
        restaurantRevPerCustomer: 22,
        hotelCostPerAvailableRoom: 182,
        hotelCostPerOccupiedRoom: 460,
        restaurantCostPerCustomer: 220,
        occupancyPct: 39,
        restaurantCustomersPerSeat: 0.6,
        hotelSatisfaction: 3.54,
        restaurantSatisfaction: 3.0,
        staffSatisfaction: 3.9,
        personnelCostPct: 340.3,
        mpi: 64.26,
        ari: 112.11,
        rgi: 72.52,
        cmpi: 100.91,
        cari: 103.21,
        crgi: 101.17,
      },
      {
        name: "SCUDERIA",
        ebitPct: -2,
        netIncome: -5391,
        goppar: 14,
        cumulativeEarnings: 270257,
        adr: 123,
        revpar: 54,
        revpor: 148,
        restaurantRevPerCustomer: 18,
        hotelCostPerAvailableRoom: 51,
        hotelCostPerOccupiedRoom: 116,
        restaurantCostPerCustomer: 55,
        occupancyPct: 44,
        restaurantCustomersPerSeat: 0.3,
        hotelSatisfaction: 3.34,
        restaurantSatisfaction: 2.45,
        staffSatisfaction: 2.68,
        personnelCostPct: 61.7,
        mpi: 72.49,
        ari: 107.48,
        rgi: 78.59,
        cmpi: 86.29,
        cari: 105.32,
        crgi: 91.26,
      },
      {
        name: "ITC Hotel",
        ebitPct: 21,
        netIncome: 38431,
        goppar: 55,
        cumulativeEarnings: 248944,
        adr: 110,
        revpar: 99,
        revpor: 151,
        restaurantRevPerCustomer: 43,
        hotelCostPerAvailableRoom: 81,
        hotelCostPerOccupiedRoom: 90,
        restaurantCostPerCustomer: 165,
        occupancyPct: 90,
        restaurantCustomersPerSeat: 0.3,
        hotelSatisfaction: 4.42,
        restaurantSatisfaction: 3.79,
        staffSatisfaction: 4.72,
        personnelCostPct: 41.2,
        mpi: 158.49,
        ari: 95.29,
        rgi: 152.34,
        cmpi: 114.65,
        cari: 103.88,
        crgi: 117.05,
      },
      {
        name: "Taj Hotels",
        ebitPct: 29,
        netIncome: 44142,
        goppar: 37,
        cumulativeEarnings: 335483,
        adr: 114,
        revpar: 65,
        revpor: 155,
        restaurantRevPerCustomer: 25,
        hotelCostPerAvailableRoom: 51,
        hotelCostPerOccupiedRoom: 90,
        restaurantCostPerCustomer: 22,
        occupancyPct: 57,
        restaurantCustomersPerSeat: 2.1,
        hotelSatisfaction: 3.96,
        restaurantSatisfaction: 3.89,
        staffSatisfaction: 4.44,
        personnelCostPct: 36.4,
        mpi: 95.39,
        ari: 99.18,
        rgi: 95.6,
        cmpi: 93.55,
        cari: 100.39,
        crgi: 94.44,
      },
      {
        name: "NOVOTEL",
        ebitPct: 16,
        netIncome: 24159,
        goppar: 47,
        cumulativeEarnings: 201136,
        adr: 108,
        revpar: 80,
        revpor: 144,
        restaurantRevPerCustomer: 22,
        hotelCostPerAvailableRoom: 60,
        hotelCostPerOccupiedRoom: 81,
        restaurantCostPerCustomer: 47,
        occupancyPct: 74,
        restaurantCustomersPerSeat: 1.1,
        hotelSatisfaction: 3.54,
        restaurantSatisfaction: 3.5,
        staffSatisfaction: 3.86,
        personnelCostPct: 50.4,
        mpi: 127.35,
        ari: 92.86,
        rgi: 119.33,
        cmpi: 108.03,
        cari: 95.61,
        crgi: 103.36,
      },
      {
        name: "Radisson Hotels",
        ebitPct: 28,
        netIncome: 32237,
        goppar: 32,
        cumulativeEarnings: 418581,
        adr: 122,
        revpar: 64,
        revpor: 153,
        restaurantRevPerCustomer: 20,
        hotelCostPerAvailableRoom: 49,
        hotelCostPerOccupiedRoom: 93,
        restaurantCostPerCustomer: 18,
        occupancyPct: 53,
        restaurantCustomersPerSeat: 1.1,
        hotelSatisfaction: 2.84,
        restaurantSatisfaction: 2.26,
        staffSatisfaction: 2.14,
        personnelCostPct: 32.6,
        mpi: 87.57,
        ari: 106.25,
        rgi: 93.96,
        cmpi: 100.11,
        cari: 100.53,
        crgi: 101.67,
      },
      {
        name: "LEELA PALACE DELHI",
        ebitPct: 26,
        netIncome: 34434,
        goppar: 31,
        cumulativeEarnings: 335600,
        adr: 117,
        revpar: 60,
        revpor: 159,
        restaurantRevPerCustomer: 21,
        hotelCostPerAvailableRoom: 51,
        hotelCostPerOccupiedRoom: 99,
        restaurantCostPerCustomer: 18,
        occupancyPct: 52,
        restaurantCustomersPerSeat: 1.8,
        hotelSatisfaction: 3.95,
        restaurantSatisfaction: 3.59,
        staffSatisfaction: 3.37,
        personnelCostPct: 36.3,
        mpi: 85.74,
        ari: 101.16,
        rgi: 87.63,
        cmpi: 95.51,
        cari: 99.54,
        crgi: 96.01,
      },
      {
        name: "HILTON HOTELS",
        ebitPct: 30,
        netIncome: 47436,
        goppar: 37,
        cumulativeEarnings: 452358,
        adr: 107,
        revpar: 64,
        revpor: 141,
        restaurantRevPerCustomer: 23,
        hotelCostPerAvailableRoom: 47,
        hotelCostPerOccupiedRoom: 78,
        restaurantCostPerCustomer: 19,
        occupancyPct: 60,
        restaurantCustomersPerSeat: 3.6,
        hotelSatisfaction: 2.96,
        restaurantSatisfaction: 3.15,
        staffSatisfaction: 2.56,
        personnelCostPct: 31.6,
        mpi: 99.85,
        ari: 92.44,
        rgi: 93.28,
        cmpi: 103.26,
        cari: 96.79,
        crgi: 100.52,
      },
      {
        name: "Lemontree",
        ebitPct: 31,
        netIncome: 67404,
        goppar: 57,
        cumulativeEarnings: 478266,
        adr: 112,
        revpar: 93,
        revpor: 146,
        restaurantRevPerCustomer: 20,
        hotelCostPerAvailableRoom: 65,
        hotelCostPerOccupiedRoom: 78,
        restaurantCostPerCustomer: 19,
        occupancyPct: 83,
        restaurantCustomersPerSeat: 4.7,
        hotelSatisfaction: 3.4,
        restaurantSatisfaction: 3.57,
        staffSatisfaction: 3.21,
        personnelCostPct: 23.9,
        mpi: 144.68,
        ari: 96.79,
        rgi: 141.4,
        cmpi: 122.42,
        cari: 95.96,
        crgi: 118.7,
      },
      {
        name: "The Oberoi's",
        ebitPct: 8,
        netIncome: 8322,
        goppar: 18,
        cumulativeEarnings: 290065,
        adr: 110,
        revpar: 66,
        revpor: 136,
        restaurantRevPerCustomer: 18,
        hotelCostPerAvailableRoom: 64,
        hotelCostPerOccupiedRoom: 106,
        restaurantCostPerCustomer: 22,
        occupancyPct: 60,
        restaurantCustomersPerSeat: 1.4,
        hotelSatisfaction: 3.67,
        restaurantSatisfaction: 3.09,
        staffSatisfaction: 3.14,
        personnelCostPct: 59.2,
        mpi: 100.6,
        ari: 94.72,
        rgi: 96.29,
        cmpi: 110.6,
        cari: 94.86,
        crgi: 105.96,
      },
      {
        name: "Hyatt Hotels",
        ebitPct: -12,
        netIncome: -19857,
        goppar: 9,
        cumulativeEarnings: 114341,
        adr: 116,
        revpar: 56,
        revpor: 147,
        restaurantRevPerCustomer: 21,
        hotelCostPerAvailableRoom: 61,
        hotelCostPerOccupiedRoom: 128,
        restaurantCostPerCustomer: 279,
        occupancyPct: 48,
        restaurantCustomersPerSeat: 0.1,
        hotelSatisfaction: 3.76,
        restaurantSatisfaction: 3.41,
        staffSatisfaction: 4.41,
        personnelCostPct: 75.3,
        mpi: 79.12,
        ari: 100.98,
        rgi: 80.71,
        cmpi: 92.91,
        cari: 99.78,
        crgi: 93.59,
      },
      {
        name: "LEELA",
        ebitPct: 30,
        netIncome: 32404,
        goppar: 34,
        cumulativeEarnings: 111134,
        adr: 116,
        revpar: 64,
        revpor: 142,
        restaurantRevPerCustomer: 23,
        hotelCostPerAvailableRoom: 45,
        hotelCostPerOccupiedRoom: 81,
        restaurantCostPerCustomer: 25,
        occupancyPct: 55,
        restaurantCustomersPerSeat: 0.8,
        hotelSatisfaction: 2.6,
        restaurantSatisfaction: 2.47,
        staffSatisfaction: 2.0,
        personnelCostPct: 27.7,
        mpi: 91.88,
        ari: 101.09,
        rgi: 93.84,
        cmpi: 77.36,
        cari: 104.56,
        crgi: 80.06,
      },
    ],
  },
];
