import { createFileRoute, Link } from "@tanstack/react-router";
import { useState, useMemo } from "react";
import { PageHeader } from "@/components/AppShell";
import { UNIVERSES_DATA, type UniverseData, type HotelMetrics } from "@/lib/universes-data";
import { PointsChart, type PointsChartDataPoint } from "@/components/ui/points-chart";
import {
  BarChart,
  Bar,
  Cell,
  XAxis,
  YAxis,
  Tooltip,
  ReferenceLine,
  ResponsiveContainer,
  CartesianGrid,
} from "recharts";
import {
  Globe,
  ArrowLeft,
  Award,
  TrendingDown,
  BarChart3,
  DollarSign,
  Users,
  HelpCircle,
  CheckCircle2,
  TrendingUp,
  Building2,
  Info,
  Star,
  Zap,
  LayoutGrid,
  BarChart2,
  Trophy,
  Activity,
} from "lucide-react";
import { cn } from "@/lib/utils";

export const Route = createFileRoute("/student/courses/$id")({
  component: StudentUniverseDetailPage,
});

function StudentUniverseDetailPage() {
  const { id } = Route.useParams();
  const universe = UNIVERSES_DATA.find((u) => u.id === id) || UNIVERSES_DATA[0];

  const [activeTab, setActiveTab] = useState<
    "profitability" | "trend-chart" | "revenue-costs" | "operations" | "str-indices" | "summary"
  >("profitability");

  const [selectedMetric, setSelectedMetric] = useState<"netIncome" | "ebitPct" | "goppar" | "cumulativeEarnings">("netIncome");
  const [chartViewMode, setChartViewMode] = useState<"barchart" | "cards">("barchart");

  // Sorted hotels for chart rendering
  const sortedHotels = useMemo(() => {
    return universe.hotels
      .slice()
      .sort((a, b) => (b[selectedMetric] as number) - (a[selectedMetric] as number));
  }, [universe, selectedMetric]);

  // Recharts data formatted
  const chartData = useMemo(() => {
    return sortedHotels.map((h, index) => ({
      name: h.name,
      value: h[selectedMetric] as number,
      rank: index + 1,
      occupancy: h.occupancyPct,
      revpar: h.revpar,
    }));
  }, [sortedHotels, selectedMetric]);

  // Top Hotel & Average Calculations for Trend
  const topHotel = universe.hotels.reduce((prev, curr) => (curr.cumulativeEarnings > prev.cumulativeEarnings ? curr : prev));
  const avgCumulative = Math.round(universe.hotels.reduce((sum, h) => sum + h.cumulativeEarnings, 0) / universe.hotels.length);

  const trendData: PointsChartDataPoint[] = [
    { date: "Round 0", total: 0, change: 0 },
    { date: "Round 2", total: Math.round(topHotel.cumulativeEarnings * 0.15), change: Math.round(topHotel.cumulativeEarnings * 0.15) },
    { date: "Round 4", total: Math.round(topHotel.cumulativeEarnings * 0.38), change: Math.round(topHotel.cumulativeEarnings * 0.23) },
    { date: "Round 6", total: Math.round(topHotel.cumulativeEarnings * 0.65), change: Math.round(topHotel.cumulativeEarnings * 0.27) },
    { date: "Round 8", total: Math.round(topHotel.cumulativeEarnings * 0.88), change: Math.round(topHotel.cumulativeEarnings * 0.23) },
    { date: "Round 9", total: topHotel.cumulativeEarnings, change: Math.round(topHotel.cumulativeEarnings * 0.12) },
  ];

  // Metric Explanations in Simple English
  const metricExplanations: Record<string, { title: string; desc: string }> = {
    netIncome: {
      title: "Net Income (€)",
      desc: "Net Income is the actual cash profit left over in Round 9 after deducting all operating expenses, hotel staff wages, and restaurant costs.",
    },
    ebitPct: {
      title: "EBIT Margin (%)",
      desc: "Operating Profit Margin (EBIT %) measures how efficiently management converts revenue into real profit. Higher positive % means superior operational control.",
    },
    goppar: {
      title: "GOPPAR (€)",
      desc: "Gross Operating Profit Per Available Room (GOPPAR) measures the operating profit generated by each room in the hotel, regardless of whether it was occupied.",
    },
    cumulativeEarnings: {
      title: "Cumulative Earnings (€)",
      desc: "Total accumulated profit or loss across all 9 simulation rounds combined. Demonstrates long-term business sustainability.",
    },
  };

  return (
    <div className="space-y-6 pb-12">
      {/* Page Header */}
      <PageHeader
        title={universe.title}
        subtitle={`${universe.simulationName} · ${universe.round} (${universe.totalHotels} Hotels Competing)`}
        action={
          <Link
            to="/student/courses"
            className="px-4 py-2 rounded-xl border border-[#e5e5e5] bg-white text-xs font-semibold text-[#0a0a0a] hover:bg-[#faf5e8] transition-colors flex items-center gap-1.5 shadow-xs"
          >
            <ArrowLeft className="w-4 h-4" /> Back to Universes
          </Link>
        }
      />

      {/* Simple English Explanation Box for Students */}
      <div className="bg-[#fffaf0] border border-[#e8b94a]/30 rounded-3xl p-5 shadow-xs space-y-3">
        <div className="flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-[#e8b94a]">
          <HelpCircle className="w-4 h-4" />
          <span>Student Guide: What does this report mean in simple terms?</span>
        </div>
        <p className="text-xs text-[#0a0a0a] leading-relaxed font-normal">
          You are exploring <strong>Universe {universe.number}</strong> after <strong>Round 9</strong>. All <strong>{universe.totalHotels} hotels</strong> competed in the exact same market. The charts and scorecards below show which hotels earned profits and which suffered losses.
        </p>

        <div className="grid sm:grid-cols-3 gap-3 pt-1 text-xs">
          <div className="bg-white/90 p-3 rounded-2xl border border-[#e5e5e5] space-y-1">
            <span className="font-bold text-[#0a0a0a] block">1. Operating Profit (EBIT %)</span>
            <span className="text-[#6a6a6a] text-[11px] leading-snug">The % of revenue kept as profit after paying operating costs. Higher is better.</span>
          </div>
          <div className="bg-white/90 p-3 rounded-2xl border border-[#e5e5e5] space-y-1">
            <span className="font-bold text-[#0a0a0a] block">2. Room Revenue (RevPAR)</span>
            <span className="text-[#6a6a6a] text-[11px] leading-snug">Combines room price (ADR) and occupancy % to measure room earning power.</span>
          </div>
          <div className="bg-white/90 p-3 rounded-2xl border border-[#e5e5e5] space-y-1">
            <span className="font-bold text-[#0a0a0a] block">3. STR Index &gt; 100</span>
            <span className="text-[#6a6a6a] text-[11px] leading-snug">Any index score above 100 means performing better than the market average.</span>
          </div>
        </div>
      </div>

      {/* Navigation Tabs */}
      <div className="flex items-center gap-2 border-b border-[#e5e5e5] pb-3 overflow-x-auto">
        {[
          { id: "profitability", label: "1. Profitability & Visual Chart" },
          { id: "trend-chart", label: "2. Performance Trend Line" },
          { id: "revenue-costs", label: "3. Revenue & Costs" },
          { id: "operations", label: "4. Occupancy & Ratings" },
          { id: "str-indices", label: "5. STR Market Indices" },
          { id: "summary", label: "6. Executive Takeaways" },
        ].map((tab) => (
          <button
            key={tab.id}
            onClick={() => setActiveTab(tab.id as any)}
            className={cn(
              "px-4 py-2.5 rounded-2xl text-xs font-semibold transition-all shrink-0 border",
              activeTab === tab.id
                ? "bg-[#0a0a0a] text-white border-[#0a0a0a] shadow-xs"
                : "bg-white text-[#6a6a6a] border-[#e5e5e5] hover:bg-[#fffaf0] hover:text-[#0a0a0a]",
            )}
          >
            {tab.label}
          </button>
        ))}
      </div>

      {/* TAB 1: PROFITABILITY & VISUAL CHART */}
      {activeTab === "profitability" && (
        <div className="space-y-6">
          {/* Performers Highlights */}
          <div className="grid md:grid-cols-2 gap-4">
            <div className="p-4 rounded-3xl bg-white border border-[#e5e5e5] shadow-xs space-y-2">
              <div className="flex items-center gap-2 text-xs font-bold text-[#0a0a0a] uppercase tracking-wider">
                <Trophy className="w-4 h-4 text-[#e8b94a]" /> Top Performer — {universe.topPerformer}
              </div>
              <p className="text-xs text-[#6a6a6a] leading-relaxed">{universe.topPerformerReason}</p>
            </div>

            <div className="p-4 rounded-3xl bg-white border border-[#e5e5e5] shadow-xs space-y-2">
              <div className="flex items-center gap-2 text-xs font-bold text-[#0a0a0a] uppercase tracking-wider">
                <Building2 className="w-4 h-4 text-[#6a6a6a]" /> Lowest Margin / Loss — {universe.bottomPerformer}
              </div>
              <p className="text-xs text-[#6a6a6a] leading-relaxed">{universe.bottomPerformerReason}</p>
            </div>
          </div>

          {/* Interactive Recharts Chart Component */}
          <div className="bg-white border border-[#e5e5e5] rounded-3xl p-6 shadow-xs space-y-5">
            {/* Controls Bar: Metric Filters + View Switcher */}
            <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 pb-4 border-b border-[#e5e5e5]">
              <div>
                <h3 className="text-base font-bold text-[#0a0a0a]">
                  Hotel Performance Scorecard ({metricExplanations[selectedMetric].title})
                </h3>
                <p className="text-xs text-[#6a6a6a] mt-0.5">
                  Visual ranking of all {universe.totalHotels} hotels competing in Universe {universe.number}
                </p>
              </div>

              <div className="flex flex-wrap items-center gap-3">
                {/* Metric Selector Buttons */}
                <div className="flex items-center gap-1 bg-[#fffaf0] p-1 rounded-2xl border border-[#e5e5e5]">
                  {[
                    { id: "netIncome", label: "Net Income (€)" },
                    { id: "ebitPct", label: "EBIT %" },
                    { id: "goppar", label: "GOPPAR (€)" },
                    { id: "cumulativeEarnings", label: "Cumulative (€)" },
                  ].map((m) => (
                    <button
                      key={m.id}
                      onClick={() => setSelectedMetric(m.id as any)}
                      className={cn(
                        "px-3 py-1.5 rounded-xl text-xs font-semibold transition-all shrink-0",
                        selectedMetric === m.id
                          ? "bg-[#0a0a0a] text-white shadow-xs"
                          : "text-[#6a6a6a] hover:text-[#0a0a0a]",
                      )}
                    >
                      {m.label}
                    </button>
                  ))}
                </div>

                {/* Chart vs Leaderboard Toggle */}
                <div className="flex items-center gap-1 bg-white p-1 rounded-2xl border border-[#e5e5e5]">
                  <button
                    onClick={() => setChartViewMode("barchart")}
                    className={cn(
                      "p-1.5 rounded-xl text-xs font-semibold transition-all flex items-center gap-1",
                      chartViewMode === "barchart"
                        ? "bg-[#0a0a0a] text-white"
                        : "text-[#6a6a6a] hover:bg-[#fffaf0]",
                    )}
                    title="Interactive Bar Chart View"
                  >
                    <BarChart2 className="w-4 h-4" />
                    <span className="hidden sm:inline text-xs">Chart</span>
                  </button>
                  <button
                    onClick={() => setChartViewMode("cards")}
                    className={cn(
                      "p-1.5 rounded-xl text-xs font-semibold transition-all flex items-center gap-1",
                      chartViewMode === "cards"
                        ? "bg-[#0a0a0a] text-white"
                        : "text-[#6a6a6a] hover:bg-[#fffaf0]",
                    )}
                    title="Detailed Leaderboard View"
                  >
                    <LayoutGrid className="w-4 h-4" />
                    <span className="hidden sm:inline text-xs">Leaderboard</span>
                  </button>
                </div>
              </div>
            </div>

            {/* Educational Metric Explanation Callout */}
            <div className="p-3.5 rounded-2xl bg-[#fffaf0] border border-[#e8b94a]/30 text-xs text-[#0a0a0a] flex items-start gap-2.5">
              <Info className="w-4 h-4 text-[#e8b94a] shrink-0 mt-0.5" />
              <div>
                <strong>Student Concept ({metricExplanations[selectedMetric].title}):</strong>{" "}
                <span className="text-[#6a6a6a]">{metricExplanations[selectedMetric].desc}</span>
              </div>
            </div>

            {/* VIEW MODE 1: RECHARTS BAR CHART */}
            {chartViewMode === "barchart" && (
              <div className="pt-2">
                <div className="h-[360px] w-full">
                  <ResponsiveContainer width="100%" height="100%">
                    <BarChart
                      data={chartData}
                      layout="vertical"
                      margin={{ top: 10, right: 30, left: 40, bottom: 10 }}
                    >
                      <CartesianGrid stroke="#f0f0f0" strokeDasharray="3 3" horizontal={false} />
                      <XAxis
                        type="number"
                        tick={{ fill: "#6a6a6a", fontSize: 11 }}
                        tickFormatter={(val) =>
                          selectedMetric === "ebitPct"
                            ? `${val}%`
                            : `${val >= 0 ? "€" : "-€"}${Math.abs(val).toLocaleString()}`
                        }
                      />
                      <YAxis
                        dataKey="name"
                        type="category"
                        width={110}
                        tick={{ fill: "#0a0a0a", fontSize: 11, fontWeight: 600 }}
                      />
                      <ReferenceLine x={0} stroke="#0a0a0a" strokeWidth={1.5} />
                      <Tooltip
                        cursor={{ fill: "rgba(232, 185, 74, 0.08)" }}
                        content={({ active, payload }) => {
                          if (!active || !payload?.length) return null;
                          const data = payload[0].payload;
                          const val = data.value;
                          return (
                            <div className="bg-[#0a0a0a] text-white rounded-2xl p-3 shadow-xl border border-[#0a0a0a] text-xs space-y-1.5 min-w-[180px]">
                              <div className="flex items-center justify-between gap-2 border-b border-white/10 pb-1 font-bold">
                                <span>{data.name}</span>
                                <span className="text-[#e8b94a] text-[10px] uppercase font-bold">
                                  Rank #{data.rank}
                                </span>
                              </div>
                              <div className="flex items-center justify-between text-xs font-semibold">
                                <span className="text-[#9a9a9a]">
                                  {metricExplanations[selectedMetric].title}:
                                </span>
                                <span className={val >= 0 ? "text-[#22c55e]" : "text-[#f43f5e]"}>
                                  {selectedMetric === "ebitPct"
                                    ? `${val}%`
                                    : `${val >= 0 ? "€" : "-€"}${Math.abs(val).toLocaleString()}`}
                                </span>
                              </div>
                              <div className="text-[11px] text-[#9a9a9a] pt-1 flex justify-between border-t border-white/10">
                                <span>Occupancy: {data.occupancy}%</span>
                                <span>RevPAR: €{data.revpar}</span>
                              </div>
                            </div>
                          );
                        }}
                      />
                      <Bar dataKey="value" radius={[0, 6, 6, 0]}>
                        {chartData.map((entry, index) => (
                          <Cell
                            key={`cell-${index}`}
                            fill={
                              entry.value >= 0
                                ? index === 0
                                  ? "#e8b94a" // Top performer gold accent
                                  : "#0a0a0a" // Solid elegant dark bar
                                : "#ef4444" // Crimson for loss
                            }
                          />
                        ))}
                      </Bar>
                    </BarChart>
                  </ResponsiveContainer>
                </div>
              </div>
            )}

            {/* VIEW MODE 2: DETAILED LEADERBOARD SCORECARD CARDS */}
            {chartViewMode === "cards" && (
              <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-3.5 pt-2">
                {sortedHotels.map((h, idx) => {
                  const val = h[selectedMetric] as number;

                  return (
                    <div
                      key={h.name}
                      className={cn(
                        "p-4 rounded-2xl border transition-all space-y-2 bg-white hover:border-[#0a0a0a]/30",
                        idx === 0
                          ? "border-[#e8b94a] bg-[#fffaf0]/40 shadow-xs"
                          : "border-[#e5e5e5]",
                      )}
                    >
                      <div className="flex items-center justify-between gap-2">
                        <span className="flex items-center gap-1.5 font-bold text-xs text-[#0a0a0a]">
                          {idx === 0 ? (
                            <span className="text-base">👑</span>
                          ) : (
                            <span className="w-5 h-5 rounded-full bg-[#0a0a0a]/5 text-[10px] flex items-center justify-center text-[#6a6a6a]">
                              #{idx + 1}
                            </span>
                          )}
                          {h.name}
                        </span>
                        <span
                          className={cn(
                            "text-xs font-bold px-2 py-0.5 rounded-lg border",
                            val >= 0
                              ? "bg-[#0a0a0a] text-white border-[#0a0a0a]"
                              : "bg-[#ef4444]/10 text-[#ef4444] border-[#ef4444]/30",
                          )}
                        >
                          {selectedMetric === "ebitPct"
                            ? `${val}%`
                            : val >= 0
                            ? `€${val.toLocaleString()}`
                            : `-€${Math.abs(val).toLocaleString()}`}
                        </span>
                      </div>

                      <div className="grid grid-cols-2 gap-2 text-[11px] pt-1 text-[#6a6a6a] border-t border-[#e5e5e5]/60">
                        <div>
                          <span className="block text-[10px] text-[#9a9a9a] uppercase font-semibold">Occupancy</span>
                          <span className="font-semibold text-[#0a0a0a]">{h.occupancyPct}%</span>
                        </div>
                        <div>
                          <span className="block text-[10px] text-[#9a9a9a] uppercase font-semibold">RevPAR</span>
                          <span className="font-semibold text-[#0a0a0a]">€{h.revpar}</span>
                        </div>
                        <div>
                          <span className="block text-[10px] text-[#9a9a9a] uppercase font-semibold">Room ADR</span>
                          <span className="font-semibold text-[#0a0a0a]">€{h.adr}</span>
                        </div>
                        <div>
                          <span className="block text-[10px] text-[#9a9a9a] uppercase font-semibold">Guest Rating</span>
                          <span className="font-semibold text-[#e8b94a]">{h.hotelSatisfaction.toFixed(1)} ★</span>
                        </div>
                      </div>
                    </div>
                  );
                })}
              </div>
            )}
          </div>

          {/* Full Data Table */}
          <div className="bg-white border border-[#e5e5e5] rounded-3xl overflow-hidden shadow-xs p-5 space-y-4">
            <h3 className="font-bold text-sm text-[#0a0a0a]">Full Profitability Data Table — Universe {universe.number}</h3>
            <div className="overflow-x-auto">
              <table className="w-full text-xs text-left">
                <thead className="bg-[#fffaf0] border-b border-[#e5e5e5] text-[#9a9a9a] uppercase font-bold text-[10px] tracking-wider">
                  <tr>
                    <th className="px-4 py-3">Hotel Name</th>
                    <th className="px-4 py-3">EBIT %</th>
                    <th className="px-4 py-3">Net Income (€)</th>
                    <th className="px-4 py-3">GOPPAR (€)</th>
                    <th className="px-4 py-3">Cumulative Earnings (€)</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-[#e5e5e5]">
                  {universe.hotels.map((h) => (
                    <tr key={h.name} className="hover:bg-[#fffaf0]/50 transition-colors">
                      <td className="px-4 py-3 font-bold text-[#0a0a0a]">{h.name}</td>
                      <td className="px-4 py-3 font-semibold">
                        <span className={h.ebitPct >= 0 ? "text-[#0a0a0a]" : "text-[#ef4444]"}>
                          {h.ebitPct}%
                        </span>
                      </td>
                      <td className="px-4 py-3 font-semibold">
                        <span className={h.netIncome >= 0 ? "text-[#0a0a0a]" : "text-[#ef4444]"}>
                          {h.netIncome >= 0 ? `€${h.netIncome.toLocaleString()}` : `-€${Math.abs(h.netIncome).toLocaleString()}`}
                        </span>
                      </td>
                      <td className="px-4 py-3 font-medium">€{h.goppar}</td>
                      <td className="px-4 py-3 font-semibold">
                        <span className={h.cumulativeEarnings >= 0 ? "text-[#0a0a0a]" : "text-[#ef4444]"}>
                          {h.cumulativeEarnings >= 0 ? `€${h.cumulativeEarnings.toLocaleString()}` : `-€${Math.abs(h.cumulativeEarnings).toLocaleString()}`}
                        </span>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      )}

      {/* TAB 2: PERFORMANCE TREND LINE */}
      {activeTab === "trend-chart" && (
        <div className="space-y-6">
          <PointsChart
            title={`Cumulative Earnings Trajectory — ${topHotel.name} (Universe ${universe.number})`}
            data={trendData}
            height={300}
            yAxisLabel="Earnings (€)"
            levels={[
              { value: avgCumulative, color: "#e8b94a" },
            ]}
          />

          <div className="p-5 bg-white border border-[#e5e5e5] rounded-3xl shadow-xs space-y-2">
            <h4 className="font-bold text-sm text-[#0a0a0a] flex items-center gap-2">
              <Zap className="w-4 h-4 text-[#e8b94a]" /> Trend Line Explanation for Students
            </h4>
            <p className="text-xs text-[#6a6a6a] leading-relaxed">
              This line chart displays how market leader <strong>{topHotel.name}</strong> accumulated earnings across Rounds 0 through 9 to reach <strong>€{topHotel.cumulativeEarnings.toLocaleString()}</strong>. The dashed gold reference line represents the Universe {universe.number} market average of <strong>€{avgCumulative.toLocaleString()}</strong>.
            </p>
          </div>
        </div>
      )}

      {/* TAB 3: REVENUE & COSTS */}
      {activeTab === "revenue-costs" && (
        <div className="space-y-6">
          <div className="p-4 bg-white border border-[#e5e5e5] rounded-3xl shadow-xs space-y-1.5">
            <h3 className="font-bold text-sm text-[#0a0a0a] flex items-center gap-2">
              <DollarSign className="w-4 h-4 text-[#e8b94a]" /> What is ADR vs RevPAR?
            </h3>
            <p className="text-xs text-[#6a6a6a] leading-relaxed">
              <strong>ADR (Average Daily Rate)</strong> is room price per night. <strong>RevPAR (Revenue Per Available Room)</strong> is total room revenue divided by all available rooms. High prices with low occupancy lead to poor RevPAR.
            </p>
          </div>

          <div className="bg-white border border-[#e5e5e5] rounded-3xl overflow-hidden shadow-xs p-5 space-y-4">
            <h3 className="font-bold text-sm text-[#0a0a0a]">Revenue & Operating Costs Table</h3>
            <div className="overflow-x-auto">
              <table className="w-full text-xs text-left">
                <thead className="bg-[#fffaf0] border-b border-[#e5e5e5] text-[#9a9a9a] uppercase font-bold text-[10px] tracking-wider">
                  <tr>
                    <th className="px-4 py-3">Hotel</th>
                    <th className="px-4 py-3">ADR (€)</th>
                    <th className="px-4 py-3">RevPAR (€)</th>
                    <th className="px-4 py-3">RevPOR (€)</th>
                    <th className="px-4 py-3">Cost / Avail Room (€)</th>
                    <th className="px-4 py-3">Cost / Occ Room (€)</th>
                    <th className="px-4 py-3">Rest. Cost / Cust (€)</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-[#e5e5e5]">
                  {universe.hotels.map((h) => (
                    <tr key={h.name} className="hover:bg-[#fffaf0]/50 transition-colors">
                      <td className="px-4 py-3 font-bold text-[#0a0a0a]">{h.name}</td>
                      <td className="px-4 py-3 font-medium">€{h.adr}</td>
                      <td className="px-4 py-3 font-semibold text-[#0a0a0a]">€{h.revpar}</td>
                      <td className="px-4 py-3 font-medium">€{h.revpor}</td>
                      <td className="px-4 py-3 text-[#6a6a6a]">€{h.hotelCostPerAvailableRoom}</td>
                      <td className="px-4 py-3 text-[#6a6a6a]">€{h.hotelCostPerOccupiedRoom}</td>
                      <td className="px-4 py-3 font-medium text-[#6a6a6a]">€{h.restaurantCostPerCustomer}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      )}

      {/* TAB 4: OCCUPANCY & RATINGS */}
      {activeTab === "operations" && (
        <div className="space-y-6">
          <div className="bg-white border border-[#e5e5e5] rounded-3xl p-5 shadow-xs space-y-4">
            <h3 className="font-bold text-sm text-[#0a0a0a] flex items-center gap-2">
              <Users className="w-4 h-4 text-[#0a0a0a]" /> Facility Utilization & Ratings (1 to 5 Stars)
            </h3>
            <div className="overflow-x-auto">
              <table className="w-full text-xs text-left">
                <thead className="bg-[#fffaf0] border-b border-[#e5e5e5] text-[#9a9a9a] uppercase font-bold text-[10px] tracking-wider">
                  <tr>
                    <th className="px-4 py-3">Hotel</th>
                    <th className="px-4 py-3">Hotel Occupancy %</th>
                    <th className="px-4 py-3">Rest. Cust / Seat</th>
                    <th className="px-4 py-3">Hotel Rating (1-5)</th>
                    <th className="px-4 py-3">Rest. Rating (1-5)</th>
                    <th className="px-4 py-3">Staff Rating (1-5)</th>
                    <th className="px-4 py-3">Personnel Cost %</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-[#e5e5e5]">
                  {universe.hotels.map((h) => (
                    <tr key={h.name} className="hover:bg-[#fffaf0]/50 transition-colors">
                      <td className="px-4 py-3 font-bold text-[#0a0a0a]">{h.name}</td>
                      <td className="px-4 py-3 font-semibold text-[#0a0a0a]">{h.occupancyPct}%</td>
                      <td className="px-4 py-3 font-medium">{h.restaurantCustomersPerSeat}</td>
                      <td className="px-4 py-3 font-bold text-[#e8b94a]">{h.hotelSatisfaction.toFixed(2)} ★</td>
                      <td className="px-4 py-3 font-semibold text-[#e8b94a]">{h.restaurantSatisfaction.toFixed(2)} ★</td>
                      <td className="px-4 py-3 font-semibold text-[#0a0a0a]">{h.staffSatisfaction.toFixed(2)} ★</td>
                      <td className="px-4 py-3 font-medium text-[#6a6a6a]">{h.personnelCostPct}%</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      )}

      {/* TAB 5: STR MARKET INDICES */}
      {activeTab === "str-indices" && (
        <div className="space-y-6">
          <div className="p-4 bg-white border border-[#e5e5e5] rounded-3xl shadow-xs space-y-1.5">
            <h3 className="font-bold text-sm text-[#0a0a0a] flex items-center gap-2">
              <BarChart3 className="w-4 h-4 text-[#0a0a0a]" /> STR Competitive Benchmark Indices
            </h3>
            <p className="text-xs text-[#6a6a6a] leading-relaxed">
              MPI = Occupancy Index | ARI = Price Index | RGI = Revenue Index.
              <strong> Index &gt; 100 = Beats Market Average</strong> | <strong> Index &lt; 100 = Below Market Average</strong>.
            </p>
          </div>

          <div className="bg-white border border-[#e5e5e5] rounded-3xl overflow-hidden shadow-xs p-5 space-y-4">
            <h3 className="font-bold text-sm text-[#0a0a0a]">STR Market Benchmark Matrix</h3>
            <div className="overflow-x-auto">
              <table className="w-full text-xs text-left">
                <thead className="bg-[#fffaf0] border-b border-[#e5e5e5] text-[#9a9a9a] uppercase font-bold text-[10px] tracking-wider">
                  <tr>
                    <th className="px-4 py-3">Hotel</th>
                    <th className="px-4 py-3">MPI (Occupancy)</th>
                    <th className="px-4 py-3">ARI (Price)</th>
                    <th className="px-4 py-3">RGI (Revenue)</th>
                    <th className="px-4 py-3">CMPI (Cum. Occupancy)</th>
                    <th className="px-4 py-3">CARI (Cum. Price)</th>
                    <th className="px-4 py-3">CRGI (Cum. Revenue)</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-[#e5e5e5]">
                  {universe.hotels.map((h) => (
                    <tr key={h.name} className="hover:bg-[#fffaf0]/50 transition-colors">
                      <td className="px-4 py-3 font-bold text-[#0a0a0a]">{h.name}</td>
                      <td className="px-4 py-3 font-semibold">{h.mpi}</td>
                      <td className="px-4 py-3 font-semibold">{h.ari}</td>
                      <td className="px-4 py-3 font-bold text-[#0a0a0a]">{h.rgi}</td>
                      <td className="px-4 py-3 text-[#6a6a6a]">{h.cmpi}</td>
                      <td className="px-4 py-3 text-[#6a6a6a]">{h.cari}</td>
                      <td className="px-4 py-3 font-semibold text-[#0a0a0a]">{h.crgi}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      )}

      {/* TAB 6: EXECUTIVE TAKEAWAYS */}
      {activeTab === "summary" && (
        <div className="space-y-6">
          <div className="bg-white border border-[#e5e5e5] rounded-3xl p-6 shadow-xs space-y-4">
            <h3 className="font-bold text-sm text-[#0a0a0a] flex items-center gap-2">
              <CheckCircle2 className="w-4 h-4 text-[#e8b94a]" /> Key Takeaways for Students — Universe {universe.number}
            </h3>

            <div className="space-y-3">
              {universe.keyInsights.map((insight, idx) => (
                <div key={idx} className="p-4 rounded-2xl bg-[#fffaf0] border border-[#e8b94a]/30 text-xs font-semibold text-[#0a0a0a] flex items-start gap-3">
                  <span className="w-5 h-5 rounded-full bg-[#0a0a0a] text-white flex items-center justify-center text-[10px] shrink-0 font-bold">
                    {idx + 1}
                  </span>
                  <span className="leading-relaxed font-medium">{insight}</span>
                </div>
              ))}
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
