import { createFileRoute, Link } from "@tanstack/react-router";
import { useState, useMemo } from "react";
import { PageHeader } from "@/components/AppShell";
import { UNIVERSES_DATA, type UniverseData, type HotelMetrics } from "@/lib/universes-data";
import { PointsChart, type PointsChartDataPoint } from "@/components/ui/points-chart";
import {
  BarChart,
  Bar,
  Cell,
  XAxis,
  YAxis,
  Tooltip,
  ReferenceLine,
  ResponsiveContainer,
  CartesianGrid,
} from "recharts";
import {
  Globe,
  ArrowLeft,
  Award,
  TrendingDown,
  BarChart3,
  DollarSign,
  Users,
  HelpCircle,
  CheckCircle2,
  TrendingUp,
  Building2,
  Info,
  Star,
  Zap,
  LayoutGrid,
  BarChart2,
  Trophy,
  Activity,
} from "lucide-react";
import { cn } from "@/lib/utils";

export const Route = createFileRoute("/teacher/courses/$id")({
  component: TeacherUniverseDetailPage,
});

function TeacherUniverseDetailPage() {
  const { id } = Route.useParams();
  const universe = UNIVERSES_DATA.find((u) => u.id === id) || UNIVERSES_DATA[0];

  const [activeTab, setActiveTab] = useState<
    "profitability" | "trend-chart" | "revenue-costs" | "operations" | "str-indices" | "summary"
  >("profitability");

  const [selectedMetric, setSelectedMetric] = useState<"netIncome" | "ebitPct" | "goppar" | "cumulativeEarnings">("netIncome");
  const [chartViewMode, setChartViewMode] = useState<"barchart" | "cards">("barchart");

  // Sorted hotels for chart rendering
  const sortedHotels = useMemo(() => {
    return universe.hotels
      .slice()
      .sort((a, b) => (b[selectedMetric] as number) - (a[selectedMetric] as number));
  }, [universe, selectedMetric]);

  // Recharts data formatted
  const chartData = useMemo(() => {
    return sortedHotels.map((h, index) => ({
      name: h.name,
      value: h[selectedMetric] as number,
      rank: index + 1,
      occupancy: h.occupancyPct,
      revpar: h.revpar,
    }));
  }, [sortedHotels, selectedMetric]);

  // Top Hotel & Average Calculations for Trend
  const topHotel = universe.hotels.reduce((prev, curr) => (curr.cumulativeEarnings > prev.cumulativeEarnings ? curr : prev));
  const avgCumulative = Math.round(universe.hotels.reduce((sum, h) => sum + h.cumulativeEarnings, 0) / universe.hotels.length);

  const trendData: PointsChartDataPoint[] = [
    { date: "Round 0", total: 0, change: 0 },
    { date: "Round 2", total: Math.round(topHotel.cumulativeEarnings * 0.15), change: Math.round(topHotel.cumulativeEarnings * 0.15) },
    { date: "Round 4", total: Math.round(topHotel.cumulativeEarnings * 0.38), change: Math.round(topHotel.cumulativeEarnings * 0.23) },
    { date: "Round 6", total: Math.round(topHotel.cumulativeEarnings * 0.65), change: Math.round(topHotel.cumulativeEarnings * 0.27) },
    { date: "Round 8", total: Math.round(topHotel.cumulativeEarnings * 0.88), change: Math.round(topHotel.cumulativeEarnings * 0.23) },
    { date: "Round 9", total: topHotel.cumulativeEarnings, change: Math.round(topHotel.cumulativeEarnings * 0.12) },
  ];

  // Metric Explanations in Simple English
  const metricExplanations: Record<string, { title: string; desc: string }> = {
    netIncome: {
      title: "Net Income (€)",
      desc: "Net Income is the actual cash profit left over in Round 9 after deducting all operating expenses, hotel staff wages, and restaurant costs.",
    },
    ebitPct: {
      title: "EBIT Margin (%)",
      desc: "Operating Profit Margin (EBIT %) measures how efficiently management converts revenue into real profit. Higher positive % means superior operational control.",
    },
    goppar: {
      title: "GOPPAR (€)",
      desc: "Gross Operating Profit Per Available Room (GOPPAR) measures the operating profit generated by each room in the hotel, regardless of whether it was occupied.",
    },
    cumulativeEarnings: {
      title: "Cumulative Earnings (€)",
      desc: "Total accumulated profit or loss across all 9 simulation rounds combined. Demonstrates long-term business sustainability.",
    },
  };

  return (
    <div className="space-y-6 pb-12">
      {/* Page Header */}
      <PageHeader
        title={universe.title}
        subtitle={`${universe.simulationName} · ${universe.round} (${universe.totalHotels} Hotels Competing)`}
        action={
          <Link
            to="/teacher/courses"
            className="px-4 py-2 rounded-xl border border-[#e5e5e5] bg-white text-xs font-semibold text-[#0a0a0a] hover:bg-[#faf5e8] transition-colors flex items-center gap-1.5 shadow-xs"
          >
            <ArrowLeft className="w-4 h-4" /> Back to Universes
          </Link>
        }
      />

      {/* Guide Box */}
      <div className="bg-[#fffaf0] border border-[#e8b94a]/30 rounded-3xl p-5 shadow-xs space-y-3">
        <div className="flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-[#e8b94a]">
          <HelpCircle className="w-4 h-4" />
          <span>Faculty Simulation Guide: Round 9 Scorecard Analysis</span>
        </div>
        <p className="text-xs text-[#0a0a0a] leading-relaxed font-normal">
          You are reviewing <strong>Universe {universe.number}</strong> after <strong>Round 9</strong>. All <strong>{universe.totalHotels} hotels</strong> competed in the exact same market. Use the tabs below to analyze student team performance, EBIT margins, RevPAR ratios, and market share indices.
        </p>

        <div className="grid sm:grid-cols-3 gap-3 pt-1 text-xs">
          <div className="bg-white/90 p-3 rounded-2xl border border-[#e5e5e5] space-y-1">
            <span className="font-bold text-[#0a0a0a] block">1. Operating Profit (EBIT %)</span>
            <span className="text-[#6a6a6a] text-[11px] leading-snug">The % of revenue kept as profit after paying operating costs. Higher is better.</span>
          </div>
          <div className="bg-white/90 p-3 rounded-2xl border border-[#e5e5e5] space-y-1">
            <span className="font-bold text-[#0a0a0a] block">2. Room Revenue (RevPAR)</span>
            <span className="text-[#6a6a6a] text-[11px] leading-snug">Combines room price (ADR) and occupancy % to measure room earning power.</span>
          </div>
          <div className="bg-white/90 p-3 rounded-2xl border border-[#e5e5e5] space-y-1">
            <span className="font-bold text-[#0a0a0a] block">3. STR Index &gt; 100</span>
            <span className="text-[#6a6a6a] text-[11px] leading-snug">Any index score above 100 means performing better than the market average.</span>
          </div>
        </div>
      </div>

      {/* Navigation Tabs */}
      <div className="flex items-center gap-2 border-b border-[#e5e5e5] pb-3 overflow-x-auto">
        {[
          { id: "profitability", label: "1. Profitability & Visual Chart" },
          { id: "trend-chart", label: "2. Performance Trend Line" },
          { id: "revenue-costs", label: "3. Revenue & Costs" },
          { id: "operations", label: "4. Occupancy & Ratings" },
          { id: "str-indices", label: "5. STR Market Indices" },
          { id: "summary", label: "6. Executive Takeaways" },
        ].map((tab) => (
          <button
            key={tab.id}
            onClick={() => setActiveTab(tab.id as any)}
            className={cn(
              "px-4 py-2.5 rounded-2xl text-xs font-semibold transition-all shrink-0 border",
              activeTab === tab.id
                ? "bg-[#0a0a0a] text-white border-[#0a0a0a] shadow-xs"
                : "bg-white text-[#6a6a6a] border-[#e5e5e5] hover:bg-[#fffaf0] hover:text-[#0a0a0a]",
            )}
          >
            {tab.label}
          </button>
        ))}
      </div>

      {/* TAB 1: PROFITABILITY & VISUAL CHART */}
      {activeTab === "profitability" && (
        <div className="space-y-6">
          <div className="grid md:grid-cols-2 gap-4">
            <div className="p-4 rounded-3xl bg-white border border-[#e5e5e5] shadow-xs space-y-2">
              <div className="flex items-center gap-2 text-xs font-bold text-[#0a0a0a] uppercase tracking-wider">
                <Trophy className="w-4 h-4 text-[#e8b94a]" /> Top Performer — {universe.topPerformer}
              </div>
              <p className="text-xs text-[#6a6a6a] leading-relaxed">{universe.topPerformerReason}</p>
            </div>

            <div className="p-4 rounded-3xl bg-white border border-[#e5e5e5] shadow-xs space-y-2">
              <div className="flex items-center gap-2 text-xs font-bold text-[#0a0a0a] uppercase tracking-wider">
                <Building2 className="w-4 h-4 text-[#6a6a6a]" /> Lowest Margin / Loss — {universe.bottomPerformer}
              </div>
              <p className="text-xs text-[#6a6a6a] leading-relaxed">{universe.bottomPerformerReason}</p>
            </div>
          </div>

          <div className="bg-white border border-[#e5e5e5] rounded-3xl p-6 shadow-xs space-y-5">
            <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 pb-4 border-b border-[#e5e5e5]">
              <div>
                <h3 className="text-base font-bold text-[#0a0a0a]">
                  Hotel Performance Scorecard ({metricExplanations[selectedMetric].title})
                </h3>
                <p className="text-xs text-[#6a6a6a] mt-0.5">
                  Visual ranking of all {universe.totalHotels} hotels competing in Universe {universe.number}
                </p>
              </div>

              <div className="flex flex-wrap items-center gap-3">
                <div className="flex items-center gap-1 bg-[#fffaf0] p-1 rounded-2xl border border-[#e5e5e5]">
                  {[
                    { id: "netIncome", label: "Net Income (€)" },
                    { id: "ebitPct", label: "EBIT %" },
                    { id: "goppar", label: "GOPPAR (€)" },
                    { id: "cumulativeEarnings", label: "Cumulative (€)" },
                  ].map((m) => (
                    <button
                      key={m.id}
                      onClick={() => setSelectedMetric(m.id as any)}
                      className={cn(
                        "px-3 py-1.5 rounded-xl text-xs font-semibold transition-all shrink-0",
                        selectedMetric === m.id
                          ? "bg-[#0a0a0a] text-white shadow-xs"
                          : "text-[#6a6a6a] hover:text-[#0a0a0a]",
                      )}
                    >
                      {m.label}
                    </button>
                  ))}
                </div>

                <div className="flex items-center gap-1 bg-white p-1 rounded-2xl border border-[#e5e5e5]">
                  <button
                    onClick={() => setChartViewMode("barchart")}
                    className={cn(
                      "p-1.5 rounded-xl text-xs font-semibold transition-all flex items-center gap-1",
                      chartViewMode === "barchart"
                        ? "bg-[#0a0a0a] text-white"
                        : "text-[#6a6a6a] hover:bg-[#fffaf0]",
                    )}
                  >
                    <BarChart2 className="w-4 h-4" />
                    <span className="hidden sm:inline text-xs">Chart</span>
                  </button>
                  <button
                    onClick={() => setChartViewMode("cards")}
                    className={cn(
                      "p-1.5 rounded-xl text-xs font-semibold transition-all flex items-center gap-1",
                      chartViewMode === "cards"
                        ? "bg-[#0a0a0a] text-white"
                        : "text-[#6a6a6a] hover:bg-[#fffaf0]",
                    )}
                  >
                    <LayoutGrid className="w-4 h-4" />
                    <span className="hidden sm:inline text-xs">Leaderboard</span>
                  </button>
                </div>
              </div>
            </div>

            <div className="p-3.5 rounded-2xl bg-[#fffaf0] border border-[#e8b94a]/30 text-xs text-[#0a0a0a] flex items-start gap-2.5">
              <Info className="w-4 h-4 text-[#e8b94a] shrink-0 mt-0.5" />
              <div>
                <strong>Metric Guide ({metricExplanations[selectedMetric].title}):</strong>{" "}
                <span className="text-[#6a6a6a]">{metricExplanations[selectedMetric].desc}</span>
              </div>
            </div>

            {chartViewMode === "barchart" && (
              <div className="pt-2">
                <div className="h-[360px] w-full">
                  <ResponsiveContainer width="100%" height="100%">
                    <BarChart
                      data={chartData}
                      layout="vertical"
                      margin={{ top: 10, right: 30, left: 40, bottom: 10 }}
                    >
                      <CartesianGrid stroke="#f0f0f0" strokeDasharray="3 3" horizontal={false} />
                      <XAxis
                        type="number"
                        tick={{ fill: "#6a6a6a", fontSize: 11 }}
                        tickFormatter={(val) =>
                          selectedMetric === "ebitPct"
                            ? `${val}%`
                            : `${val >= 0 ? "€" : "-€"}${Math.abs(val).toLocaleString()}`
                        }
                      />
                      <YAxis
                        dataKey="name"
                        type="category"
                        width={110}
                        tick={{ fill: "#0a0a0a", fontSize: 11, fontWeight: 600 }}
                      />
                      <ReferenceLine x={0} stroke="#0a0a0a" strokeWidth={1.5} />
                      <Tooltip
                        cursor={{ fill: "rgba(232, 185, 74, 0.08)" }}
                        content={({ active, payload }) => {
                          if (!active || !payload?.length) return null;
                          const data = payload[0].payload;
                          const val = data.value;
                          return (
                            <div className="bg-[#0a0a0a] text-white p-3 rounded-2xl shadow-xl text-xs space-y-1 font-sans">
                              <div className="font-bold border-b border-white/20 pb-1">
                                #{data.rank} {data.name}
                              </div>
                              <div className="text-[#e8b94a] font-mono">
                                {metricExplanations[selectedMetric].title}:{" "}
                                {selectedMetric === "ebitPct"
                                  ? `${val}%`
                                  : `${val >= 0 ? "€" : "-€"}${Math.abs(val).toLocaleString()}`}
                              </div>
                              <div className="text-[11px] text-gray-300">
                                Occupancy: {data.occupancy}% · RevPAR: €{data.revpar}
                              </div>
                            </div>
                          );
                        }}
                      />
                      <Bar dataKey="value" radius={[0, 6, 6, 0]}>
                        {chartData.map((entry, index) => {
                          const isProfitable = entry.value >= 0;
                          return (
                            <Cell
                              key={`cell-${index}`}
                              fill={isProfitable ? (index === 0 ? "#e8b94a" : "#0a0a0a") : "#ef4444"}
                            />
                          );
                        })}
                      </Bar>
                    </BarChart>
                  </ResponsiveContainer>
                </div>
              </div>
            )}

            {chartViewMode === "cards" && (
              <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4 pt-2">
                {sortedHotels.map((h, index) => {
                  const val = h[selectedMetric] as number;
                  const isPositive = val >= 0;
                  return (
                    <div
                      key={h.name}
                      className={cn(
                        "p-4 rounded-2xl border transition-all flex flex-col justify-between space-y-3",
                        index === 0
                          ? "bg-[#fffaf0] border-[#e8b94a] shadow-xs"
                          : "bg-white border-[#e5e5e5]",
                      )}
                    >
                      <div className="flex items-center justify-between">
                        <span
                          className={cn(
                            "text-[10px] font-mono font-bold px-2 py-0.5 rounded-full border",
                            index === 0
                              ? "bg-[#e8b94a] text-black border-[#e8b94a]"
                              : "bg-[#0a0a0a]/5 text-[#0a0a0a] border-[#0a0a0a]/10",
                          )}
                        >
                          RANK #{index + 1}
                        </span>
                        <span className="text-[11px] text-[#6a6a6a] font-medium">
                          {h.occupancyPct}% Occ.
                        </span>
                      </div>

                      <div>
                        <h4 className="font-bold text-sm text-[#0a0a0a]">{h.name}</h4>
                        <div
                          className={cn(
                            "text-lg font-extrabold mt-1 font-mono",
                            isPositive ? (index === 0 ? "text-[#0a0a0a]" : "text-[#15803d]") : "text-[#ef4444]",
                          )}
                        >
                          {selectedMetric === "ebitPct"
                            ? `${val}% EBIT`
                            : `${val >= 0 ? "€" : "-€"}${Math.abs(val).toLocaleString()}`}
                        </div>
                      </div>

                      <div className="pt-2 border-t border-[#e5e5e5]/60 grid grid-cols-2 gap-2 text-[11px] text-[#6a6a6a]">
                        <div>RevPAR: <strong className="text-[#0a0a0a]">€{h.revpar}</strong></div>
                        <div>ADR: <strong className="text-[#0a0a0a]">€{h.adr}</strong></div>
                      </div>
                    </div>
                  );
                })}
              </div>
            )}

            {/* Profitability Data Table */}
            <div className="pt-4 space-y-3">
              <h4 className="text-xs font-bold uppercase tracking-wider text-[#0a0a0a]">
                Full Profitability Data Table — Universe {universe.number}
              </h4>
              <div className="overflow-x-auto">
                <table className="w-full text-xs text-left">
                  <thead className="bg-[#fffaf0] border-b border-[#e5e5e5] text-[#9a9a9a] uppercase font-semibold text-[10px] tracking-wider">
                    <tr>
                      <th className="px-4 py-3">Hotel Name</th>
                      <th className="px-4 py-3">EBIT %</th>
                      <th className="px-4 py-3">Net Income (€)</th>
                      <th className="px-4 py-3">GOPPAR (€)</th>
                      <th className="px-4 py-3">Cumulative Earnings (€)</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-[#e5e5e5]">
                    {universe.hotels.map((h) => (
                      <tr key={h.name} className="hover:bg-[#fffaf0]/40 transition-colors">
                        <td className="px-4 py-3 font-semibold text-[#0a0a0a]">{h.name}</td>
                        <td className={cn("px-4 py-3 font-mono font-bold", h.ebitPct >= 0 ? "text-[#15803d]" : "text-[#ef4444]")}>
                          {h.ebitPct}%
                        </td>
                        <td className={cn("px-4 py-3 font-mono font-bold", h.netIncome >= 0 ? "text-[#0a0a0a]" : "text-[#ef4444]")}>
                          {h.netIncome >= 0 ? `€${h.netIncome.toLocaleString()}` : `-€${Math.abs(h.netIncome).toLocaleString()}`}
                        </td>
                        <td className="px-4 py-3 font-mono text-[#0a0a0a]">€{h.goppar}</td>
                        <td className={cn("px-4 py-3 font-mono font-bold", h.cumulativeEarnings >= 0 ? "text-[#0a0a0a]" : "text-[#ef4444]")}>
                          {h.cumulativeEarnings >= 0 ? `€${h.cumulativeEarnings.toLocaleString()}` : `-€${Math.abs(h.cumulativeEarnings).toLocaleString()}`}
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* TAB 2: PERFORMANCE TREND LINE */}
      {activeTab === "trend-chart" && (
        <div className="bg-white border border-[#e5e5e5] rounded-3xl p-6 shadow-xs space-y-6">
          <div>
            <h3 className="text-base font-bold text-[#0a0a0a]">
              Cumulative Earnings Growth (Round 0 to Round 9)
            </h3>
            <p className="text-xs text-[#6a6a6a] mt-0.5">
              Historical progression of market leader ({topHotel.name}) vs industry benchmark average.
            </p>
          </div>

          <div className="bg-[#fffaf0] border border-[#e5e5e5] rounded-2xl p-5">
            <PointsChart data={trendData} color="#e8b94a" />
          </div>

          <div className="grid sm:grid-cols-2 gap-4 text-xs">
            <div className="p-4 rounded-2xl bg-white border border-[#e5e5e5] space-y-1">
              <span className="text-[#6a6a6a] font-medium block">Market Leader Total</span>
              <span className="text-xl font-extrabold text-[#0a0a0a]">€{topHotel.cumulativeEarnings.toLocaleString()}</span>
              <span className="text-[11px] text-[#22c55e] block font-semibold">{topHotel.name} (Top Net Performer)</span>
            </div>
            <div className="p-4 rounded-2xl bg-white border border-[#e5e5e5] space-y-1">
              <span className="text-[#6a6a6a] font-medium block">Industry Benchmark Average</span>
              <span className="text-xl font-extrabold text-[#0a0a0a]">€{avgCumulative.toLocaleString()}</span>
              <span className="text-[11px] text-[#6a6a6a] block font-medium">Average across {universe.totalHotels} hotels</span>
            </div>
          </div>
        </div>
      )}

      {/* TAB 3: REVENUE & COSTS */}
      {activeTab === "revenue-costs" && (
        <div className="bg-white border border-[#e5e5e5] rounded-3xl p-6 shadow-xs space-y-4">
          <h3 className="text-base font-bold text-[#0a0a0a]">
            Revenue Ratios & Cost Breakdown (€)
          </h3>
          <div className="overflow-x-auto">
            <table className="w-full text-xs text-left">
              <thead className="bg-[#fffaf0] border-b border-[#e5e5e5] text-[#9a9a9a] uppercase font-semibold text-[10px] tracking-wider">
                <tr>
                  <th className="px-4 py-3">Hotel Name</th>
                  <th className="px-4 py-3">ADR (€)</th>
                  <th className="px-4 py-3">RevPAR (€)</th>
                  <th className="px-4 py-3">RevPOR (€)</th>
                  <th className="px-4 py-3">CPOR (€)</th>
                  <th className="px-4 py-3">Personnel Cost %</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-[#e5e5e5]">
                {universe.hotels.map((h) => (
                  <tr key={h.name} className="hover:bg-[#fffaf0]/40 transition-colors">
                    <td className="px-4 py-3 font-semibold text-[#0a0a0a]">{h.name}</td>
                    <td className="px-4 py-3 font-mono font-bold text-[#0a0a0a]">€{h.adr}</td>
                    <td className="px-4 py-3 font-mono font-bold text-[#e8b94a]">€{h.revpar}</td>
                    <td className="px-4 py-3 font-mono text-[#0a0a0a]">€{h.revpor}</td>
                    <td className="px-4 py-3 font-mono text-[#6a6a6a]">€{h.hotelCostPerOccupiedRoom}</td>
                    <td className={cn("px-4 py-3 font-mono font-bold", h.personnelCostPct > 45 ? "text-[#ef4444]" : "text-[#15803d]")}>
                      {h.personnelCostPct}%
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}

      {/* TAB 4: OCCUPANCY & RATINGS */}
      {activeTab === "operations" && (
        <div className="bg-white border border-[#e5e5e5] rounded-3xl p-6 shadow-xs space-y-4">
          <h3 className="text-base font-bold text-[#0a0a0a]">
            Occupancy & Guest/Staff Satisfaction Ratios
          </h3>
          <div className="overflow-x-auto">
            <table className="w-full text-xs text-left">
              <thead className="bg-[#fffaf0] border-b border-[#e5e5e5] text-[#9a9a9a] uppercase font-semibold text-[10px] tracking-wider">
                <tr>
                  <th className="px-4 py-3">Hotel Name</th>
                  <th className="px-4 py-3">Occupancy %</th>
                  <th className="px-4 py-3">Hotel Satisfaction (/5)</th>
                  <th className="px-4 py-3">Restaurant Satisfaction (/5)</th>
                  <th className="px-4 py-3">Staff Satisfaction (/5)</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-[#e5e5e5]">
                {universe.hotels.map((h) => (
                  <tr key={h.name} className="hover:bg-[#fffaf0]/40 transition-colors">
                    <td className="px-4 py-3 font-semibold text-[#0a0a0a]">{h.name}</td>
                    <td className="px-4 py-3 font-mono font-bold text-[#0a0a0a]">{h.occupancyPct}%</td>
                    <td className="px-4 py-3 font-mono text-[#e8b94a] font-bold">{h.hotelSatisfaction}</td>
                    <td className="px-4 py-3 font-mono text-[#0a0a0a]">{h.restaurantSatisfaction}</td>
                    <td className="px-4 py-3 font-mono text-[#0a0a0a]">{h.staffSatisfaction}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}

      {/* TAB 5: STR MARKET INDICES */}
      {activeTab === "str-indices" && (
        <div className="bg-white border border-[#e5e5e5] rounded-3xl p-6 shadow-xs space-y-4">
          <h3 className="text-base font-bold text-[#0a0a0a]">
            STR Market Indices (Base = 100)
          </h3>
          <div className="overflow-x-auto">
            <table className="w-full text-xs text-left">
              <thead className="bg-[#fffaf0] border-b border-[#e5e5e5] text-[#9a9a9a] uppercase font-semibold text-[10px] tracking-wider">
                <tr>
                  <th className="px-4 py-3">Hotel Name</th>
                  <th className="px-4 py-3">MPI (Market Penetration Index)</th>
                  <th className="px-4 py-3">ARI (Average Rate Index)</th>
                  <th className="px-4 py-3">RGI (Revenue Generation Index)</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-[#e5e5e5]">
                {universe.hotels.map((h) => (
                  <tr key={h.name} className="hover:bg-[#fffaf0]/40 transition-colors">
                    <td className="px-4 py-3 font-semibold text-[#0a0a0a]">{h.name}</td>
                    <td className={cn("px-4 py-3 font-mono font-bold", h.mpi >= 100 ? "text-[#15803d]" : "text-[#ef4444]")}>{h.mpi}</td>
                    <td className={cn("px-4 py-3 font-mono font-bold", h.ari >= 100 ? "text-[#15803d]" : "text-[#ef4444]")}>{h.ari}</td>
                    <td className={cn("px-4 py-3 font-mono font-bold", h.rgi >= 100 ? "text-[#e8b94a]" : "text-[#ef4444]")}>{h.rgi}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}

      {/* TAB 6: EXECUTIVE TAKEAWAYS */}
      {activeTab === "summary" && (
        <div className="bg-white border border-[#e5e5e5] rounded-3xl p-6 shadow-xs space-y-4">
          <h3 className="text-base font-bold text-[#0a0a0a]">
            Faculty & Executive Market Insights — Round 9 Summary
          </h3>
          <div className="space-y-3">
            {universe.keyInsights.map((insight, idx) => (
              <div key={idx} className="p-4 rounded-2xl bg-[#fffaf0] border border-[#e8b94a]/30 text-xs text-[#0a0a0a] flex items-start gap-3">
                <span className="font-bold font-mono text-[#e8b94a] shrink-0">0{idx + 1}.</span>
                <p className="leading-relaxed">{insight}</p>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}
