/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as LabRouteImport } from './routes/lab'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as StudentRouteImport } from './routes/student'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminActivityRouteImport } from './routes/admin.activity'
import { Route as AdminAnnouncementsRouteImport } from './routes/admin.announcements'
import { Route as AdminAttendanceRouteImport } from './routes/admin.attendance'
import { Route as AdminCoursesRouteImport } from './routes/admin.courses'
import { Route as AdminProfileRouteImport } from './routes/admin.profile'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminResourcesRouteImport } from './routes/admin.resources'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminTasksRouteImport } from './routes/admin.tasks'
import { Route as AdminTeachersRouteImport } from './routes/admin.teachers'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as StudentIndexRouteImport } from './routes/student.index'
import { Route as StudentAssignmentsRouteImport } from './routes/student.assignments'
import { Route as StudentAttendanceRouteImport } from './routes/student.attendance'
import { Route as StudentLabRouteImport } from './routes/student.lab'
import { Route as StudentProfileRouteImport } from './routes/student.profile'
import { Route as StudentResourcesRouteImport } from './routes/student.resources'
import { Route as TeacherIndexRouteImport } from './routes/teacher.index'
import { Route as TeacherAttendanceRouteImport } from './routes/teacher.attendance'
import { Route as TeacherProfileRouteImport } from './routes/teacher.profile'
import { Route as TeacherSubmissionsRouteImport } from './routes/teacher.submissions'
import { Route as StudentCoursesIndexRouteImport } from './routes/student.courses.index'
import { Route as StudentCoursesIdRouteImport } from './routes/student.courses.$id'
import { Route as StudentTasksIndexRouteImport } from './routes/student.tasks.index'
import { Route as StudentTasksIdRouteImport } from './routes/student.tasks.$id'
import { Route as TeacherAnnouncementsNewRouteImport } from './routes/teacher.announcements.new'
import { Route as TeacherCoursesIndexRouteImport } from './routes/teacher.courses.index'
import { Route as TeacherCoursesIdRouteImport } from './routes/teacher.courses.$id'
import { Route as TeacherResourcesNewRouteImport } from './routes/teacher.resources.new'
import { Route as TeacherTasksNewRouteImport } from './routes/teacher.tasks.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const LabRoute = LabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminActivityRoute = AdminActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnnouncementsRoute = AdminAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAttendanceRoute = AdminAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoursesRoute = AdminCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminResourcesRoute = AdminResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTasksRoute = AdminTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTeachersRoute = AdminTeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRoute,
} as any)
const StudentAssignmentsRoute = StudentAssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => StudentRoute,
} as any)
const StudentAttendanceRoute = StudentAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => StudentRoute,
} as any)
const StudentLabRoute = StudentLabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => StudentRoute,
} as any)
const StudentProfileRoute = StudentProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => StudentRoute,
} as any)
const StudentResourcesRoute = StudentResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => StudentRoute,
} as any)
const TeacherIndexRoute = TeacherIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherAttendanceRoute = TeacherAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherProfileRoute = TeacherProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherSubmissionsRoute = TeacherSubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => TeacherRoute,
} as any)
const StudentCoursesIndexRoute = StudentCoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => StudentRoute,
} as any)
const StudentCoursesIdRoute = StudentCoursesIdRouteImport.update({
  id: '/courses/$id',
  path: '/courses/$id',
  getParentRoute: () => StudentRoute,
} as any)
const StudentTasksIndexRoute = StudentTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => StudentRoute,
} as any)
const StudentTasksIdRoute = StudentTasksIdRouteImport.update({
  id: '/tasks/$id',
  path: '/tasks/$id',
  getParentRoute: () => StudentRoute,
} as any)
const TeacherAnnouncementsNewRoute = TeacherAnnouncementsNewRouteImport.update({
  id: '/announcements/new',
  path: '/announcements/new',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherCoursesIndexRoute = TeacherCoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherCoursesIdRoute = TeacherCoursesIdRouteImport.update({
  id: '/courses/$id',
  path: '/courses/$id',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherResourcesNewRoute = TeacherResourcesNewRouteImport.update({
  id: '/resources/new',
  path: '/resources/new',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherTasksNewRoute = TeacherTasksNewRouteImport.update({
  id: '/tasks/new',
  path: '/tasks/new',
  getParentRoute: () => TeacherRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/calendar': typeof CalendarRoute
  '/lab': typeof LabRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/student': typeof StudentRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/verify-email': typeof VerifyEmailRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/resources': typeof AdminResourcesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tasks': typeof AdminTasksRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/admin/users': typeof AdminUsersRoute
  '/student/assignments': typeof StudentAssignmentsRoute
  '/student/attendance': typeof StudentAttendanceRoute
  '/student/lab': typeof StudentLabRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/resources': typeof StudentResourcesRoute
  '/teacher/attendance': typeof TeacherAttendanceRoute
  '/teacher/profile': typeof TeacherProfileRoute
  '/teacher/submissions': typeof TeacherSubmissionsRoute
  '/admin/': typeof AdminIndexRoute
  '/student/': typeof StudentIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/student/courses/$id': typeof StudentCoursesIdRoute
  '/student/tasks/$id': typeof StudentTasksIdRoute
  '/teacher/announcements/new': typeof TeacherAnnouncementsNewRoute
  '/teacher/courses/$id': typeof TeacherCoursesIdRoute
  '/teacher/resources/new': typeof TeacherResourcesNewRoute
  '/teacher/tasks/new': typeof TeacherTasksNewRoute
  '/student/courses/': typeof StudentCoursesIndexRoute
  '/student/tasks/': typeof StudentTasksIndexRoute
  '/teacher/courses/': typeof TeacherCoursesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/lab': typeof LabRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/resources': typeof AdminResourcesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tasks': typeof AdminTasksRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/admin/users': typeof AdminUsersRoute
  '/student/assignments': typeof StudentAssignmentsRoute
  '/student/attendance': typeof StudentAttendanceRoute
  '/student/lab': typeof StudentLabRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/resources': typeof StudentResourcesRoute
  '/teacher/attendance': typeof TeacherAttendanceRoute
  '/teacher/profile': typeof TeacherProfileRoute
  '/teacher/submissions': typeof TeacherSubmissionsRoute
  '/admin': typeof AdminIndexRoute
  '/student': typeof StudentIndexRoute
  '/teacher': typeof TeacherIndexRoute
  '/student/courses/$id': typeof StudentCoursesIdRoute
  '/student/tasks/$id': typeof StudentTasksIdRoute
  '/teacher/announcements/new': typeof TeacherAnnouncementsNewRoute
  '/teacher/courses/$id': typeof TeacherCoursesIdRoute
  '/teacher/resources/new': typeof TeacherResourcesNewRoute
  '/teacher/tasks/new': typeof TeacherTasksNewRoute
  '/student/courses': typeof StudentCoursesIndexRoute
  '/student/tasks': typeof StudentTasksIndexRoute
  '/teacher/courses': typeof TeacherCoursesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/calendar': typeof CalendarRoute
  '/lab': typeof LabRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/student': typeof StudentRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/verify-email': typeof VerifyEmailRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/resources': typeof AdminResourcesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tasks': typeof AdminTasksRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/admin/users': typeof AdminUsersRoute
  '/student/assignments': typeof StudentAssignmentsRoute
  '/student/attendance': typeof StudentAttendanceRoute
  '/student/lab': typeof StudentLabRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/resources': typeof StudentResourcesRoute
  '/teacher/attendance': typeof TeacherAttendanceRoute
  '/teacher/profile': typeof TeacherProfileRoute
  '/teacher/submissions': typeof TeacherSubmissionsRoute
  '/admin/': typeof AdminIndexRoute
  '/student/': typeof StudentIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/student/courses/$id': typeof StudentCoursesIdRoute
  '/student/tasks/$id': typeof StudentTasksIdRoute
  '/teacher/announcements/new': typeof TeacherAnnouncementsNewRoute
  '/teacher/courses/$id': typeof TeacherCoursesIdRoute
  '/teacher/resources/new': typeof TeacherResourcesNewRoute
  '/teacher/tasks/new': typeof TeacherTasksNewRoute
  '/student/courses/': typeof StudentCoursesIndexRoute
  '/student/tasks/': typeof StudentTasksIndexRoute
  '/teacher/courses/': typeof TeacherCoursesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/calendar'
    | '/lab'
    | '/login'
    | '/messages'
    | '/notifications'
    | '/register'
    | '/reset-password'
    | '/student'
    | '/teacher'
    | '/verify-email'
    | '/admin/activity'
    | '/admin/announcements'
    | '/admin/attendance'
    | '/admin/courses'
    | '/admin/profile'
    | '/admin/reports'
    | '/admin/resources'
    | '/admin/settings'
    | '/admin/tasks'
    | '/admin/teachers'
    | '/admin/users'
    | '/student/assignments'
    | '/student/attendance'
    | '/student/lab'
    | '/student/profile'
    | '/student/resources'
    | '/teacher/attendance'
    | '/teacher/profile'
    | '/teacher/submissions'
    | '/admin/'
    | '/student/'
    | '/teacher/'
    | '/student/courses/$id'
    | '/student/tasks/$id'
    | '/teacher/announcements/new'
    | '/teacher/courses/$id'
    | '/teacher/resources/new'
    | '/teacher/tasks/new'
    | '/student/courses/'
    | '/student/tasks/'
    | '/teacher/courses/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/lab'
    | '/login'
    | '/messages'
    | '/notifications'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/admin/activity'
    | '/admin/announcements'
    | '/admin/attendance'
    | '/admin/courses'
    | '/admin/profile'
    | '/admin/reports'
    | '/admin/resources'
    | '/admin/settings'
    | '/admin/tasks'
    | '/admin/teachers'
    | '/admin/users'
    | '/student/assignments'
    | '/student/attendance'
    | '/student/lab'
    | '/student/profile'
    | '/student/resources'
    | '/teacher/attendance'
    | '/teacher/profile'
    | '/teacher/submissions'
    | '/admin'
    | '/student'
    | '/teacher'
    | '/student/courses/$id'
    | '/student/tasks/$id'
    | '/teacher/announcements/new'
    | '/teacher/courses/$id'
    | '/teacher/resources/new'
    | '/teacher/tasks/new'
    | '/student/courses'
    | '/student/tasks'
    | '/teacher/courses'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/calendar'
    | '/lab'
    | '/login'
    | '/messages'
    | '/notifications'
    | '/register'
    | '/reset-password'
    | '/student'
    | '/teacher'
    | '/verify-email'
    | '/admin/activity'
    | '/admin/announcements'
    | '/admin/attendance'
    | '/admin/courses'
    | '/admin/profile'
    | '/admin/reports'
    | '/admin/resources'
    | '/admin/settings'
    | '/admin/tasks'
    | '/admin/teachers'
    | '/admin/users'
    | '/student/assignments'
    | '/student/attendance'
    | '/student/lab'
    | '/student/profile'
    | '/student/resources'
    | '/teacher/attendance'
    | '/teacher/profile'
    | '/teacher/submissions'
    | '/admin/'
    | '/student/'
    | '/teacher/'
    | '/student/courses/$id'
    | '/student/tasks/$id'
    | '/teacher/announcements/new'
    | '/teacher/courses/$id'
    | '/teacher/resources/new'
    | '/teacher/tasks/new'
    | '/student/courses/'
    | '/student/tasks/'
    | '/teacher/courses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CalendarRoute: typeof CalendarRoute
  LabRoute: typeof LabRoute
  LoginRoute: typeof LoginRoute
  MessagesRoute: typeof MessagesRoute
  NotificationsRoute: typeof NotificationsRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  StudentRoute: typeof StudentRouteWithChildren
  TeacherRoute: typeof TeacherRouteWithChildren
  VerifyEmailRoute: typeof VerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab': {
      id: '/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof LabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/activity': {
      id: '/admin/activity'
      path: '/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AdminActivityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/announcements': {
      id: '/admin/announcements'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AdminAnnouncementsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/attendance': {
      id: '/admin/attendance'
      path: '/attendance'
      fullPath: '/admin/attendance'
      preLoaderRoute: typeof AdminAttendanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/courses': {
      id: '/admin/courses'
      path: '/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AdminCoursesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/resources': {
      id: '/admin/resources'
      path: '/resources'
      fullPath: '/admin/resources'
      preLoaderRoute: typeof AdminResourcesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tasks': {
      id: '/admin/tasks'
      path: '/tasks'
      fullPath: '/admin/tasks'
      preLoaderRoute: typeof AdminTasksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/teachers': {
      id: '/admin/teachers'
      path: '/teachers'
      fullPath: '/admin/teachers'
      preLoaderRoute: typeof AdminTeachersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/assignments': {
      id: '/student/assignments'
      path: '/assignments'
      fullPath: '/student/assignments'
      preLoaderRoute: typeof StudentAssignmentsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/attendance': {
      id: '/student/attendance'
      path: '/attendance'
      fullPath: '/student/attendance'
      preLoaderRoute: typeof StudentAttendanceRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/lab': {
      id: '/student/lab'
      path: '/lab'
      fullPath: '/student/lab'
      preLoaderRoute: typeof StudentLabRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/profile': {
      id: '/student/profile'
      path: '/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentProfileRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/resources': {
      id: '/student/resources'
      path: '/resources'
      fullPath: '/student/resources'
      preLoaderRoute: typeof StudentResourcesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/teacher/': {
      id: '/teacher/'
      path: '/'
      fullPath: '/teacher/'
      preLoaderRoute: typeof TeacherIndexRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/attendance': {
      id: '/teacher/attendance'
      path: '/attendance'
      fullPath: '/teacher/attendance'
      preLoaderRoute: typeof TeacherAttendanceRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/profile': {
      id: '/teacher/profile'
      path: '/profile'
      fullPath: '/teacher/profile'
      preLoaderRoute: typeof TeacherProfileRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/submissions': {
      id: '/teacher/submissions'
      path: '/submissions'
      fullPath: '/teacher/submissions'
      preLoaderRoute: typeof TeacherSubmissionsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/student/courses/': {
      id: '/student/courses/'
      path: '/courses'
      fullPath: '/student/courses/'
      preLoaderRoute: typeof StudentCoursesIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/courses/$id': {
      id: '/student/courses/$id'
      path: '/courses/$id'
      fullPath: '/student/courses/$id'
      preLoaderRoute: typeof StudentCoursesIdRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/tasks/': {
      id: '/student/tasks/'
      path: '/tasks'
      fullPath: '/student/tasks/'
      preLoaderRoute: typeof StudentTasksIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/tasks/$id': {
      id: '/student/tasks/$id'
      path: '/tasks/$id'
      fullPath: '/student/tasks/$id'
      preLoaderRoute: typeof StudentTasksIdRouteImport
      parentRoute: typeof StudentRoute
    }
    '/teacher/announcements/new': {
      id: '/teacher/announcements/new'
      path: '/announcements/new'
      fullPath: '/teacher/announcements/new'
      preLoaderRoute: typeof TeacherAnnouncementsNewRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/courses/': {
      id: '/teacher/courses/'
      path: '/courses'
      fullPath: '/teacher/courses/'
      preLoaderRoute: typeof TeacherCoursesIndexRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/courses/$id': {
      id: '/teacher/courses/$id'
      path: '/courses/$id'
      fullPath: '/teacher/courses/$id'
      preLoaderRoute: typeof TeacherCoursesIdRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/resources/new': {
      id: '/teacher/resources/new'
      path: '/resources/new'
      fullPath: '/teacher/resources/new'
      preLoaderRoute: typeof TeacherResourcesNewRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/tasks/new': {
      id: '/teacher/tasks/new'
      path: '/tasks/new'
      fullPath: '/teacher/tasks/new'
      preLoaderRoute: typeof TeacherTasksNewRouteImport
      parentRoute: typeof TeacherRoute
    }
  }
}

interface AdminRouteChildren {
  AdminActivityRoute: typeof AdminActivityRoute
  AdminAnnouncementsRoute: typeof AdminAnnouncementsRoute
  AdminAttendanceRoute: typeof AdminAttendanceRoute
  AdminCoursesRoute: typeof AdminCoursesRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminResourcesRoute: typeof AdminResourcesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTasksRoute: typeof AdminTasksRoute
  AdminTeachersRoute: typeof AdminTeachersRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminActivityRoute: AdminActivityRoute,
  AdminAnnouncementsRoute: AdminAnnouncementsRoute,
  AdminAttendanceRoute: AdminAttendanceRoute,
  AdminCoursesRoute: AdminCoursesRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminResourcesRoute: AdminResourcesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTasksRoute: AdminTasksRoute,
  AdminTeachersRoute: AdminTeachersRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface StudentRouteChildren {
  StudentAssignmentsRoute: typeof StudentAssignmentsRoute
  StudentAttendanceRoute: typeof StudentAttendanceRoute
  StudentLabRoute: typeof StudentLabRoute
  StudentProfileRoute: typeof StudentProfileRoute
  StudentResourcesRoute: typeof StudentResourcesRoute
  StudentIndexRoute: typeof StudentIndexRoute
  StudentCoursesIdRoute: typeof StudentCoursesIdRoute
  StudentTasksIdRoute: typeof StudentTasksIdRoute
  StudentCoursesIndexRoute: typeof StudentCoursesIndexRoute
  StudentTasksIndexRoute: typeof StudentTasksIndexRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentAssignmentsRoute: StudentAssignmentsRoute,
  StudentAttendanceRoute: StudentAttendanceRoute,
  StudentLabRoute: StudentLabRoute,
  StudentProfileRoute: StudentProfileRoute,
  StudentResourcesRoute: StudentResourcesRoute,
  StudentIndexRoute: StudentIndexRoute,
  StudentCoursesIdRoute: StudentCoursesIdRoute,
  StudentTasksIdRoute: StudentTasksIdRoute,
  StudentCoursesIndexRoute: StudentCoursesIndexRoute,
  StudentTasksIndexRoute: StudentTasksIndexRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

interface TeacherRouteChildren {
  TeacherAttendanceRoute: typeof TeacherAttendanceRoute
  TeacherProfileRoute: typeof TeacherProfileRoute
  TeacherSubmissionsRoute: typeof TeacherSubmissionsRoute
  TeacherIndexRoute: typeof TeacherIndexRoute
  TeacherAnnouncementsNewRoute: typeof TeacherAnnouncementsNewRoute
  TeacherCoursesIdRoute: typeof TeacherCoursesIdRoute
  TeacherResourcesNewRoute: typeof TeacherResourcesNewRoute
  TeacherTasksNewRoute: typeof TeacherTasksNewRoute
  TeacherCoursesIndexRoute: typeof TeacherCoursesIndexRoute
}

const TeacherRouteChildren: TeacherRouteChildren = {
  TeacherAttendanceRoute: TeacherAttendanceRoute,
  TeacherProfileRoute: TeacherProfileRoute,
  TeacherSubmissionsRoute: TeacherSubmissionsRoute,
  TeacherIndexRoute: TeacherIndexRoute,
  TeacherAnnouncementsNewRoute: TeacherAnnouncementsNewRoute,
  TeacherCoursesIdRoute: TeacherCoursesIdRoute,
  TeacherResourcesNewRoute: TeacherResourcesNewRoute,
  TeacherTasksNewRoute: TeacherTasksNewRoute,
  TeacherCoursesIndexRoute: TeacherCoursesIndexRoute,
}

const TeacherRouteWithChildren =
  TeacherRoute._addFileChildren(TeacherRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CalendarRoute: CalendarRoute,
  LabRoute: LabRoute,
  LoginRoute: LoginRoute,
  MessagesRoute: MessagesRoute,
  NotificationsRoute: NotificationsRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  StudentRoute: StudentRouteWithChildren,
  TeacherRoute: TeacherRouteWithChildren,
  VerifyEmailRoute: VerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
